//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GRPCChannelFactory.h"

@interface GRPCInsecureChannelFactory : NSObject <GRPCChannelFactory>
{
}

+ (id)sharedInstance;
- (struct grpc_channel *)createChannelWithHost:(id)arg1 channelArgs:(id)arg2;

@end

