//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GRPCTransportFactory.h"

@class GRPCCallOptions;

@protocol GRPCCoreTransportFactory <GRPCTransportFactory>
- (id <GRPCChannelFactory>)createCoreChannelFactoryWithCallOptions:(GRPCCallOptions *)arg1;
@end

