//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSketchPlugin/GRPCCallOptions.h>

#import "NSCopying.h"
#import "NSMutableCopying.h"

@class NSArray, NSDictionary, NSString;

@interface GRPCMutableCallOptions : GRPCCallOptions <NSCopying, NSMutableCopying>
{
}

@property unsigned long long channelID; // @dynamic channelID;
@property(copy) NSString *channelPoolDomain; // @dynamic channelPoolDomain;
@property(retain) id logContext; // @dynamic logContext;
@property(copy) NSString *hostNameOverride; // @dynamic hostNameOverride;
@property char *transport; // @dynamic transport;
@property unsigned long long transportType; // @dynamic transportType;
@property(copy) NSString *PEMCertificateChain; // @dynamic PEMCertificateChain;
@property(copy) NSString *PEMPrivateKey; // @dynamic PEMPrivateKey;
@property(copy) NSString *PEMRootCertificates; // @dynamic PEMRootCertificates;
@property(copy) NSDictionary *additionalChannelArgs; // @dynamic additionalChannelArgs;
@property double connectMaxBackoff; // @dynamic connectMaxBackoff;
@property double connectInitialBackoff; // @dynamic connectInitialBackoff;
@property double connectMinTimeout; // @dynamic connectMinTimeout;
@property double keepaliveTimeout; // @dynamic keepaliveTimeout;
@property double keepaliveInterval; // @dynamic keepaliveInterval;
@property BOOL retryEnabled; // @dynamic retryEnabled;
@property unsigned long long compressionAlgorithm; // @dynamic compressionAlgorithm;
@property unsigned long long responseSizeLimit; // @dynamic responseSizeLimit;
@property(copy) NSString *userAgentPrefix; // @dynamic userAgentPrefix;
@property(copy) NSDictionary *initialMetadata; // @dynamic initialMetadata;
@property(retain) id <GRPCAuthorizationProtocol> authTokenProvider; // @dynamic authTokenProvider;
@property(copy) NSString *oauth2AccessToken; // @dynamic oauth2AccessToken;
@property(copy) NSArray *interceptorFactories; // @dynamic interceptorFactories;
@property BOOL flowControlEnabled; // @dynamic flowControlEnabled;
@property double timeout; // @dynamic timeout;
@property(copy) NSString *serverAuthority; // @dynamic serverAuthority;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

