//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GRPCChannelFactory.h"

@interface GRPCSecureChannelFactory : NSObject <GRPCChannelFactory>
{
    struct grpc_channel_credentials *_channelCreds;
}

+ (id)factoryWithPEMRootCertificates:(id)arg1 privateKey:(id)arg2 certChain:(id)arg3 error:(id *)arg4;
- (void)dealloc;
- (struct grpc_channel *)createChannelWithHost:(id)arg1 channelArgs:(id)arg2;
- (id)initWithPEMRootCerts:(id)arg1 privateKey:(id)arg2 certChain:(id)arg3 error:(id *)arg4;
- (id)nullTerminatedDataWithString:(id)arg1;

@end

