//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GRPCCallOptions, GRPCRequestOptions;

@interface GRPCCall2 : NSObject
{
    id <GRPCResponseHandler> _responseHandler;
    id <GRPCInterceptorInterface> _firstInterceptor;
    GRPCCallOptions *_actualCallOptions;
    GRPCCallOptions *_callOptions;
    GRPCRequestOptions *_requestOptions;
}

+ (id)globalInterceptorFactory;
+ (void)registerGlobalInterceptor:(id)arg1;
@property(readonly, copy) GRPCRequestOptions *requestOptions; // @synthesize requestOptions=_requestOptions;
@property(readonly, copy) GRPCCallOptions *callOptions; // @synthesize callOptions=_callOptions;
- (void).cxx_destruct;
- (void)receiveNextMessages:(unsigned long long)arg1;
- (void)finish;
- (void)writeData:(id)arg1;
- (void)cancel;
- (void)start;
- (id)initWithRequestOptions:(id)arg1 responseHandler:(id)arg2;
- (id)initWithRequestOptions:(id)arg1 responseHandler:(id)arg2 callOptions:(id)arg3;

@end

