//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GRPCPooledChannel;

@interface GRPCWrappedCall : NSObject
{
    GRPCPooledChannel *_pooledChannel;
    struct grpc_call *_call;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)channelDisconnected;
- (void)cancel;
- (void)startBatchWithOperations:(id)arg1 errorHandler:(CDUnknownBlockType)arg2;
- (void)startBatchWithOperations:(id)arg1;
- (id)initWithUnmanagedCall:(struct grpc_call *)arg1 pooledChannel:(id)arg2;

@end

