//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface GRPCTransportRegistry : NSObject
{
    NSMutableDictionary *_registry;
    id <GRPCTransportFactory> _defaultFactory;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)getTransportFactoryWithID:(char *)arg1;
- (void)registerTransportWithID:(char *)arg1 factory:(id)arg2;
- (id)init;

@end

