//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface GRPCChannelPool : NSObject
{
    NSMutableDictionary *_channelPool;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)disconnectAllChannels;
- (id)channelWithHost:(id)arg1 callOptions:(id)arg2;
- (void)dealloc;
- (id)initPrivate;
- (id)initTestPool;

@end

