//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GRPCDispatchable.h"
#import "NSObject.h"

@class GRPCCallOptions, GRPCRequestOptions;

@protocol GRPCInterceptorInterface <NSObject, GRPCDispatchable>
- (void)receiveNextMessages:(unsigned long long)arg1;
- (void)cancel;
- (void)finish;
- (void)writeData:(id)arg1;
- (void)startWithRequestOptions:(GRPCRequestOptions *)arg1 callOptions:(GRPCCallOptions *)arg2;
@end

