//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GRPCResponseHandler.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface GRPCResponseDispatcher : NSObject <GRPCResponseHandler>
{
    id <GRPCResponseHandler> _responseHandler;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
}

- (void).cxx_destruct;
- (void)didWriteData;
- (void)didCloseWithTrailingMetadata:(id)arg1 error:(id)arg2;
- (void)didReceiveData:(id)arg1;
- (void)didReceiveInitialMetadata:(id)arg1;
@property(readonly) NSObject<OS_dispatch_queue> *dispatchQueue;
- (id)initWithResponseHandler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

