//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GRPCResponseHandler.h"

@class GRPCCall2, GRPCCallOptions, GRPCRequestOptions, NSObject<OS_dispatch_queue>, NSString;

@interface GRPCStreamingProtoCall : NSObject <GRPCResponseHandler>
{
    GRPCRequestOptions *_requestOptions;
    id <GRPCProtoResponseHandler> _handler;
    GRPCCallOptions *_callOptions;
    Class _responseClass;
    GRPCCall2 *_call;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
}

- (void).cxx_destruct;
@property(readonly) NSObject<OS_dispatch_queue> *dispatchQueue;
- (void)didWriteData;
- (void)didCloseWithTrailingMetadata:(id)arg1 error:(id)arg2;
- (void)didReceiveData:(id)arg1;
- (void)didReceiveInitialMetadata:(id)arg1;
- (void)receiveNextMessages:(unsigned long long)arg1;
- (void)receiveNextMessage;
- (void)finish;
- (void)writeMessage:(id)arg1;
- (void)cancel;
- (void)start;
- (id)initWithRequestOptions:(id)arg1 responseHandler:(id)arg2 callOptions:(id)arg3 responseClass:(Class)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

