//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GRPCInterceptorInterface.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface GRPCTransport : NSObject <GRPCInterceptorInterface>
{
}

- (void)receiveNextMessages:(unsigned long long)arg1;
- (void)finish;
- (void)cancel;
- (void)writeData:(id)arg1;
- (void)startWithRequestOptions:(id)arg1 callOptions:(id)arg2;
@property(readonly) NSObject<OS_dispatch_queue> *dispatchQueue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

