//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class GRPCCallOptions, NSDictionary, NSString;

@interface GRPCChannelConfiguration : NSObject <NSCopying>
{
    NSString *_host;
    GRPCCallOptions *_callOptions;
}

@property(readonly) GRPCCallOptions *callOptions; // @synthesize callOptions=_callOptions;
@property(readonly, copy) NSString *host; // @synthesize host=_host;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSDictionary *channelArgs;
@property(readonly) id <GRPCChannelFactory> channelFactory;
- (id)initWithHost:(id)arg1 callOptions:(id)arg2;

@end

