//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSketchPlugin/GRXImmediateWriter.h>

@interface GRXImmediateSingleWriter : GRXImmediateWriter
{
    id _value;
    long long _state;
}

+ (id)writerWithValue:(id)arg1;
- (long long)state;
- (void).cxx_destruct;
- (id)map:(CDUnknownBlockType)arg1;
- (void)setState:(long long)arg1;
- (void)startWithWriteable:(id)arg1;
- (id)initWithValue:(id)arg1;

@end

