//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFileWrapper.h"

@interface NSFileWrapper (PROExtensions)
- (id)abstract_icon;
- (void)debugPrint:(id)arg1 level:(unsigned long long)arg2;
- (void)debugPrint;
- (void)debugPrint:(id)arg1;
@end

