//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "OTTracer.h"

@interface OTNoopTracer : NSObject <OTTracer>
{
}

+ (void)initialize;
- (id)extractWithFormat:(id)arg1 carrier:(id)arg2 error:(id *)arg3;
- (id)extractWithFormat:(id)arg1 carrier:(id)arg2;
- (BOOL)inject:(id)arg1 format:(id)arg2 carrier:(id)arg3 error:(id *)arg4;
- (BOOL)inject:(id)arg1 format:(id)arg2 carrier:(id)arg3;
- (id)startSpan:(id)arg1 references:(id)arg2 tags:(id)arg3 startTime:(id)arg4;
- (id)startSpan:(id)arg1 childOf:(id)arg2 tags:(id)arg3 startTime:(id)arg4;
- (id)startSpan:(id)arg1 childOf:(id)arg2 tags:(id)arg3;
- (id)startSpan:(id)arg1 childOf:(id)arg2;
- (id)startSpan:(id)arg1 tags:(id)arg2;
- (id)startSpan:(id)arg1;

@end

