//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface OTReference : NSObject
{
    NSString *_type;
    id <OTSpanContext> _referencedContext;
}

+ (id)followsFrom:(id)arg1;
+ (id)childOf:(id)arg1;
@property(retain, nonatomic) id <OTSpanContext> referencedContext; // @synthesize referencedContext=_referencedContext;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithType:(id)arg1 referencedContext:(id)arg2;

@end

