//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDate, NSDictionary, NSNumber, NSObject, NSString;

@protocol OTSpan
- (void)finishWithTime:(NSDate *)arg1;
- (void)finish;
- (NSString *)getBaggageItem:(NSString *)arg1;
- (id <OTSpan>)setBaggageItem:(NSString *)arg1 value:(NSString *)arg2;
- (void)log:(NSString *)arg1 timestamp:(NSDate *)arg2 payload:(NSObject *)arg3;
- (void)logEvent:(NSString *)arg1 payload:(NSObject *)arg2;
- (void)logEvent:(NSString *)arg1;
- (void)log:(NSDictionary *)arg1 timestamp:(NSDate *)arg2;
- (void)log:(NSDictionary *)arg1;
- (void)setTag:(NSString *)arg1 boolValue:(BOOL)arg2;
- (void)setTag:(NSString *)arg1 numberValue:(NSNumber *)arg2;
- (void)setTag:(NSString *)arg1 value:(NSString *)arg2;
- (void)setOperationName:(NSString *)arg1;
- (id <OTTracer>)tracer;
- (id <OTSpanContext>)context;
@end

