//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSDate, NSDictionary, NSString;

@protocol OTTracer
- (id <OTSpanContext>)extractWithFormat:(NSString *)arg1 carrier:(id)arg2 error:(id *)arg3;
- (id <OTSpanContext>)extractWithFormat:(NSString *)arg1 carrier:(id)arg2;
- (BOOL)inject:(id <OTSpanContext>)arg1 format:(NSString *)arg2 carrier:(id)arg3 error:(id *)arg4;
- (BOOL)inject:(id <OTSpanContext>)arg1 format:(NSString *)arg2 carrier:(id)arg3;
- (id <OTSpan>)startSpan:(NSString *)arg1 references:(NSArray *)arg2 tags:(NSDictionary *)arg3 startTime:(NSDate *)arg4;
- (id <OTSpan>)startSpan:(NSString *)arg1 childOf:(id <OTSpanContext>)arg2 tags:(NSDictionary *)arg3 startTime:(NSDate *)arg4;
- (id <OTSpan>)startSpan:(NSString *)arg1 childOf:(id <OTSpanContext>)arg2 tags:(NSDictionary *)arg3;
- (id <OTSpan>)startSpan:(NSString *)arg1 childOf:(id <OTSpanContext>)arg2;
- (id <OTSpan>)startSpan:(NSString *)arg1 tags:(NSDictionary *)arg2;
- (id <OTSpan>)startSpan:(NSString *)arg1;
@end

