//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, PROGitController, PROSketchAbstractMetadata, PROSketchURLManager;

@interface PROAbstractSketchFileCreator : NSObject
{
    PROGitController *_gitController;
    PROSketchURLManager *_urlManager;
    PROSketchAbstractMetadata *_metadata;
    NSString *_commitSha;
    NSString *_fileTreeSha;
    NSURL *_editingURL;
}

@property(copy, nonatomic) NSURL *editingURL; // @synthesize editingURL=_editingURL;
@property(copy, nonatomic) NSString *fileTreeSha; // @synthesize fileTreeSha=_fileTreeSha;
@property(copy, nonatomic) NSString *commitSha; // @synthesize commitSha=_commitSha;
@property(retain, nonatomic) PROSketchAbstractMetadata *metadata; // @synthesize metadata=_metadata;
@property(retain, nonatomic) PROSketchURLManager *urlManager; // @synthesize urlManager=_urlManager;
@property(retain, nonatomic) PROGitController *gitController; // @synthesize gitController=_gitController;
- (void).cxx_destruct;
- (id)backupURL;
- (void)makeBackup;
- (void)removeEditingFile;
- (id)readFileTreeShaForEditingFile:(id)arg1;
- (void)saveMetadataToEditingFile:(CDUnknownBlockType)arg1;
- (BOOL)existsAtEditingURL;
- (void)saveAlreadyOpenEditingFile:(CDUnknownBlockType)arg1;
- (void)handleBranchRename:(CDUnknownBlockType)arg1;
- (void)removeCacheFile;
- (void)copyCacheEntryToEditingFileURL:(CDUnknownBlockType)arg1;
- (id)cacheURL;
- (void)createCacheEntryIfNeeded:(CDUnknownBlockType)arg1;
- (BOOL)hasChanges;
- (void)checkForChangesAndHasChanges:(CDUnknownBlockType)arg1 doesNotHaveChanges:(CDUnknownBlockType)arg2;
- (void)readEditingFileTreeSha:(id)arg1 shasMatch:(CDUnknownBlockType)arg2 shasDoNotMatch:(CDUnknownBlockType)arg3;
- (void)createEditingFile:(CDUnknownBlockType)arg1;
- (id)initWithRepoURL:(id)arg1 baseSHA:(id)arg2 projectId:(id)arg3 projectName:(id)arg4 branchId:(id)arg5 branchName:(id)arg6 fileId:(id)arg7 savePath:(id)arg8;

@end

