//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PROAbstractAPI : NSObject
{
}

+ (id)installedPlugins;
+ (void)checkResponse:(id)arg1;
+ (id)errorMessageFromResponse:(id)arg1;
+ (id)runCommand:(id)arg1 args:(id)arg2;
+ (id)reportMessage:(id)arg1 extra:(id)arg2 level:(id)arg3 fingerprint:(id)arg4;
+ (id)reportMessage:(id)arg1 extra:(id)arg2 level:(id)arg3;
+ (id)reportException:(id)arg1 extra:(id)arg2 level:(id)arg3 fingerprint:(id)arg4;
+ (id)reportException:(id)arg1 extra:(id)arg2 level:(id)arg3;
+ (void)saveToAbstractFile:(id)arg1 projectId:(id)arg2 branchId:(id)arg3 fileId:(id)arg4 name:(id)arg5;
+ (void)saveToAbstractFile:(id)arg1 meta:(id)arg2;
+ (void)importSketchFile:(id)arg1 projectId:(id)arg2 branchId:(id)arg3 fileId:(id)arg4 name:(id)arg5;
+ (id)createSketchFile:(id)arg1 fileId:(id)arg2 projectId:(id)arg3 branchId:(id)arg4 sha:(id)arg5;
+ (void)commitFile:(id)arg1 projectId:(id)arg2 branchId:(id)arg3;
+ (void)createEditingFile:(id)arg1 projectId:(id)arg2 projectName:(id)arg3 branchId:(id)arg4 sha:(id)arg5;
+ (void)createCacheFile:(id)arg1 projectId:(id)arg2 branchId:(id)arg3 sha:(id)arg4;
+ (BOOL)fileHasChanges:(id)arg1 projectId:(id)arg2;

@end

