//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface PROAbstractCommand : NSObject
{
    NSString *_command;
    NSArray *_args;
    NSDictionary *_response;
    NSDictionary *_successResponse;
    NSDictionary *_errorResponse;
}

+ (id)command:(id)arg1 withArgs:(id)arg2;
@property(retain, nonatomic) NSDictionary *errorResponse; // @synthesize errorResponse=_errorResponse;
@property(retain, nonatomic) NSDictionary *successResponse; // @synthesize successResponse=_successResponse;
@property(retain, nonatomic) NSDictionary *response; // @synthesize response=_response;
@property(retain, nonatomic) NSArray *args; // @synthesize args=_args;
@property(copy, nonatomic) NSString *command; // @synthesize command=_command;
- (void).cxx_destruct;
- (id)runNSTaskCommand:(id)arg1 args:(id)arg2;
- (id)run;

@end

