//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSString, NSUserDefaults;

@interface PROAbstractConfig : NSObject
{
    NSMutableDictionary *__config;
    NSUserDefaults *_userDefaults;
}

+ (BOOL)cliExistsAtAppPath:(id)arg1;
+ (id)cliPathWithAppPath:(id)arg1;
+ (id)defaultCLIPath;
+ (id)configFromConfig:(id)arg1 withNewValues:(id)arg2;
+ (id)configFromUserDefaults;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(retain, nonatomic) NSMutableDictionary *_config; // @synthesize _config=__config;
- (void).cxx_destruct;
- (id)defaultCLIPath;
- (id)defaultAbstractSupportPath;
- (id)defaultAbstractStorePath;
- (BOOL)isTestEnvironment;
- (BOOL)isDevelopmentEnvironment;
- (id)enabledFeatures;
- (BOOL)hasFeature:(id)arg1;
@property(readonly, nonatomic) NSDictionary *dict;
@property(readonly, nonatomic) BOOL tracingEnabled;
@property(readonly, nonatomic) BOOL sketchGoOpenFile;
@property(readonly, nonatomic) BOOL abstractdEnabled;
@property(readonly, nonatomic) BOOL librariesEnabled;
@property(readonly, nonatomic) NSString *cliPath;
@property(readonly, nonatomic) NSString *storePath;
@property(readonly, nonatomic) NSString *env;

@end

