//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSketchPlugin/PROFlippedView.h>

@class NSColor;

@interface PROCustomBackgroundColorView : PROFlippedView
{
    NSColor *_backgroundColor;
    id _delegate;
}

@property __weak id delegate; // @synthesize delegate=_delegate;
@property(retain) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

