//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface PRODocumentMessageController : NSObject
{
    NSMutableDictionary *_messages;
}

+ (id)messageController;
@property(retain, nonatomic) NSMutableDictionary *messages; // @synthesize messages=_messages;
- (void).cxx_destruct;
- (id)getMessagesForFileURL:(id)arg1;
- (void)addMessage:(id)arg1 forFileURL:(id)arg2;
- (id)init;

@end

