//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton, NSColor, NSImageView, NSObject<OS_dispatch_queue>, NSProgressIndicator, NSString, NSTextField, NSWindow, PROCustomBackgroundColorView, PROSketchAbstractMetadata, PROSketchBootstrap;

@interface PROFloatingWindowController : NSWindowController
{
    BOOL _isTopAligned;
    BOOL _isRemoved;
    BOOL _shouldPreviewAndCommitAfterSave;
    BOOL _isSavingSketchFile;
    BOOL _isSaving;
    BOOL _refreshing;
    BOOL _readOnly;
    BOOL _repoOutOfSync;
    BOOL _hasChanges;
    BOOL _isCheckingPluginVersion;
    BOOL _needsPluginUpdate;
    NSTextField *_projectLabel;
    NSTextField *_branchLabel;
    NSImageView *_abstractIcon;
    PROCustomBackgroundColorView *_backgroundView;
    NSTextField *_statusLabel;
    PROCustomBackgroundColorView *_warningArea;
    NSButton *_commitButton;
    NSTextField *_saveStatusLabel;
    NSProgressIndicator *_saveProgress;
    NSWindow *_sketchWindow;
    PROSketchAbstractMetadata *_abstractMetadata;
    PROSketchBootstrap *_bootstrap;
    NSColor *_activeColor;
    NSString *_repoOutOfSyncTitle;
    NSObject<OS_dispatch_queue> *_refreshQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *refreshQueue; // @synthesize refreshQueue=_refreshQueue;
@property(nonatomic) BOOL needsPluginUpdate; // @synthesize needsPluginUpdate=_needsPluginUpdate;
@property(nonatomic) BOOL isCheckingPluginVersion; // @synthesize isCheckingPluginVersion=_isCheckingPluginVersion;
@property(nonatomic) BOOL hasChanges; // @synthesize hasChanges=_hasChanges;
@property(copy, nonatomic) NSString *repoOutOfSyncTitle; // @synthesize repoOutOfSyncTitle=_repoOutOfSyncTitle;
@property(nonatomic) BOOL repoOutOfSync; // @synthesize repoOutOfSync=_repoOutOfSync;
@property(nonatomic) BOOL readOnly; // @synthesize readOnly=_readOnly;
@property(nonatomic) BOOL refreshing; // @synthesize refreshing=_refreshing;
@property(nonatomic) BOOL isSaving; // @synthesize isSaving=_isSaving;
@property(nonatomic) BOOL isSavingSketchFile; // @synthesize isSavingSketchFile=_isSavingSketchFile;
@property(nonatomic) BOOL shouldPreviewAndCommitAfterSave; // @synthesize shouldPreviewAndCommitAfterSave=_shouldPreviewAndCommitAfterSave;
@property(nonatomic) BOOL isRemoved; // @synthesize isRemoved=_isRemoved;
@property(nonatomic) BOOL isTopAligned; // @synthesize isTopAligned=_isTopAligned;
@property(retain, nonatomic) NSColor *activeColor; // @synthesize activeColor=_activeColor;
@property(nonatomic) __weak PROSketchBootstrap *bootstrap; // @synthesize bootstrap=_bootstrap;
@property(nonatomic) __weak PROSketchAbstractMetadata *abstractMetadata; // @synthesize abstractMetadata=_abstractMetadata;
@property(nonatomic) __weak NSWindow *sketchWindow; // @synthesize sketchWindow=_sketchWindow;
@property __weak NSProgressIndicator *saveProgress; // @synthesize saveProgress=_saveProgress;
@property __weak NSTextField *saveStatusLabel; // @synthesize saveStatusLabel=_saveStatusLabel;
@property __weak NSButton *commitButton; // @synthesize commitButton=_commitButton;
@property __weak PROCustomBackgroundColorView *warningArea; // @synthesize warningArea=_warningArea;
@property __weak NSTextField *statusLabel; // @synthesize statusLabel=_statusLabel;
@property __weak PROCustomBackgroundColorView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property __weak NSImageView *abstractIcon; // @synthesize abstractIcon=_abstractIcon;
@property __weak NSTextField *branchLabel; // @synthesize branchLabel=_branchLabel;
@property __weak NSTextField *projectLabel; // @synthesize projectLabel=_projectLabel;
- (void).cxx_destruct;
- (void)updateWindowFrame;
- (void)updateColors;
- (void)removeProjectLibraries;
- (void)addProjectLibraries;
- (void)togglePosition:(id)arg1;
- (void)commit:(id)arg1;
- (void)previewAndCommit;
- (void)mouseDown:(id)arg1;
- (void)updateUI;
- (void)checkPluginVersion;
- (void)refreshGitStatus;
- (void)finishedSaving;
- (void)startSaving;
- (void)savingSketchFile;
- (void)toggle;
- (void)removeFromSketchWindow;
- (void)addToSketchWindow;
- (void)windowDidResignMain:(id)arg1;
- (void)windowDidBecomeMain:(id)arg1;
- (void)windowDidEndSheet:(id)arg1;
- (void)windowWillBeginSheet:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (void)close;
- (void)dealloc;
- (void)windowDidLoad;
- (id)initWithAbstractMetadata:(id)arg1 bootstrap:(id)arg2;

@end

