//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDictionary;

@interface PROLogRecord : NSObject
{
    NSDate *_timestamp;
    NSDictionary *_fields;
}

@property(readonly, nonatomic) NSDictionary *fields; // @synthesize fields=_fields;
@property(readonly, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (id)toRPC;
- (id)initWithTimestamp:(id)arg1 fields:(id)arg2;

@end

