//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSketchPlugin/GPBMessage.h>

@class NSData, NSString;

@interface PRORPCTraceTag : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *key; // @dynamic key;
@property(copy, nonatomic) NSData *vBinary; // @dynamic vBinary;
@property(nonatomic) BOOL vBool; // @dynamic vBool;
@property(nonatomic) double vDouble; // @dynamic vDouble;
@property(nonatomic) long long vLong; // @dynamic vLong;
@property(copy, nonatomic) NSString *vStr; // @dynamic vStr;
@property(nonatomic) int vType; // @dynamic vType;

@end

