//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSketchPlugin/GPBMessage.h>

@class NSMutableArray, PRORPCConfig;

@interface PRORPCTraceBatchSpanRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) PRORPCConfig *config; // @dynamic config;
@property(nonatomic) BOOL hasConfig; // @dynamic hasConfig;
@property(retain, nonatomic) NSMutableArray *spanArray; // @dynamic spanArray;
@property(readonly, nonatomic) unsigned long long spanArray_Count; // @dynamic spanArray_Count;

@end

