//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSketchPlugin/GPBMessage.h>

@class PRORPCConfig, PRORPCTraceSpan;

@interface PRORPCTraceSpanRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) PRORPCConfig *config; // @dynamic config;
@property(nonatomic) BOOL hasConfig; // @dynamic hasConfig;
@property(nonatomic) BOOL hasSpan; // @dynamic hasSpan;
@property(retain, nonatomic) PRORPCTraceSpan *span; // @dynamic span;

@end

