//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSketchPlugin/GPBMessage.h>

@class NSMutableArray, NSString, PRORPCUser;

@interface PRORPCConfig : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *apiURL; // @dynamic apiURL;
@property(retain, nonatomic) NSMutableArray *bundleIdsArray; // @dynamic bundleIdsArray;
@property(readonly, nonatomic) unsigned long long bundleIdsArray_Count; // @dynamic bundleIdsArray_Count;
@property(nonatomic) BOOL hasUser; // @dynamic hasUser;
@property(copy, nonatomic) NSString *orsURL; // @dynamic orsURL;
@property(copy, nonatomic) NSString *remoteURL; // @dynamic remoteURL;
@property(copy, nonatomic) NSString *storePath; // @dynamic storePath;
@property(retain, nonatomic) PRORPCUser *user; // @dynamic user;

@end

