//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GRPCProtoCall, PRORPCTraceSpanRequest;

@protocol PRORPCTraceService <NSObject>
- (GRPCProtoCall *)RPCToSpanWithRequest:(PRORPCTraceSpanRequest *)arg1 handler:(void (^)(PRORPCTraceSpanResponse *, NSError *))arg2;
- (void)spanWithRequest:(PRORPCTraceSpanRequest *)arg1 handler:(void (^)(PRORPCTraceSpanResponse *, NSError *))arg2;
@end

