//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSketchPlugin/GRPCProtoService.h>

#import "PRORPCTraceService.h"
#import "PRORPCTraceService2.h"

@class NSString;

@interface PRORPCTraceService : GRPCProtoService <PRORPCTraceService2, PRORPCTraceService>
{
}

+ (id)serviceWithHost:(id)arg1 callOptions:(id)arg2;
+ (id)serviceWithHost:(id)arg1;
- (id)spanWithMessage:(id)arg1 responseHandler:(id)arg2 callOptions:(id)arg3;
- (id)RPCToSpanWithRequest:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)spanWithRequest:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)initWithHost:(id)arg1 packageName:(id)arg2 serviceName:(id)arg3 callOptions:(id)arg4;
- (id)initWithHost:(id)arg1 packageName:(id)arg2 serviceName:(id)arg3;
- (id)initWithHost:(id)arg1;
- (id)initWithHost:(id)arg1 callOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

