//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface PROSketchFileUserPreferences : NSObject
{
    id _identifier;
    NSMutableDictionary *_preferences;
}

@property(retain, nonatomic) NSMutableDictionary *preferences; // @synthesize preferences=_preferences;
@property(retain, nonatomic) id identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)preferencesURL;
- (id)fileURL;
- (void)load;
- (id)key:(id)arg1 withIdentifier:(id)arg2;
- (id)prefValueForKey:(id)arg1 withIdentifier:(id)arg2;
- (id)prefValueForKey:(id)arg1;
- (void)setPrefValue:(id)arg1 forKey:(id)arg2 withIdentifier:(id)arg3;
- (void)setPrefValue:(id)arg1 forKey:(id)arg2;
- (void)save;
- (id)initWithDocumentIdentifier:(id)arg1;

@end

