//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PROAbstractConfig, PROSketchInstance;

@interface PROSketchURLManager : NSObject
{
    PROSketchInstance *_sketchInstance;
    PROAbstractConfig *_config;
}

@property(retain, nonatomic) PROAbstractConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) PROSketchInstance *sketchInstance; // @synthesize sketchInstance=_sketchInstance;
- (void).cxx_destruct;
- (void)reportMessage:(id)arg1 fingerprint:(id)arg2;
- (void)showSketchError;
- (void)createDirectory:(id)arg1;
- (void)ensureDirectoriesExist;
- (id)storeURL;
- (id)reposURL;
- (id)tmpURL;
- (id)editingURL;
- (id)abstractDocumentsURL;
- (id)sanitizedFilePathPart:(id)arg1;
- (id)repoURL:(id)arg1;
- (id)sketchFilename:(id)arg1;
- (id)tmpFileURL:(id)arg1;
- (id)editFileURL:(id)arg1 fileId:(id)arg2 branchId:(id)arg3 sha:(id)arg4;
- (id)cachedFileURL:(id)arg1 fileSha:(id)arg2;
- (id)cacheURLForProject:(id)arg1;
- (id)initWithSketchInstance:(id)arg1 config:(id)arg2;

@end

