//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSDocument, PROSketchCommander;

@interface PROSketchDocumentService : NSObject
{
    MSDocument *_document;
    PROSketchCommander *_commander;
}

@property(retain, nonatomic) PROSketchCommander *commander; // @synthesize commander=_commander;
@property(nonatomic) __weak MSDocument *document; // @synthesize document=_document;
- (void).cxx_destruct;
- (id)findLayerWithPersistentIdentifier:(id)arg1 rootLayer:(id)arg2;
- (id)fetchPersistentIdentifier:(id)arg1;
- (id)selectedLayersExcept:(id)arg1;
- (id)selectedLayers;
- (void)ensureConsistentIdentifiersForLayerTree:(id)arg1;
- (void)refresh;
- (id)initWithDocument:(id)arg1 commander:(id)arg2;

@end

