//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PROSketchDocumentUtils : NSObject
{
}

+ (id)documents;
+ (void)closeDocument:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)closeDocument:(id)arg1;
+ (void)saveDocumentAndSkipAbstractVersion:(id)arg1 url:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)displayReadDocument:(id)arg1;
+ (void)openAndDisplaySketchURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)openSketchURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)readDocument:(id)arg1 error:(id *)arg2;
+ (id)openDocument:(id)arg1;
+ (id)createEmptyDocument;

@end

