//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSDocument, NSMutableArray, NSTimer, PROFloatingWindowController, PROSketchAbstractMetadata, SketchDocumentFilePresenter;

@interface PROSketchBootstrap : NSObject
{
    MSDocument *_document;
    PROSketchAbstractMetadata *_abstractMetadata;
    id _documentKey;
    SketchDocumentFilePresenter *_filePresenter;
    long long _saveCount;
    PROFloatingWindowController *_floatingWindowController;
    NSTimer *_isCommittingTimer;
    NSMutableArray *_saveOps;
}

+ (void)teardownBatbeltForDocument:(id)arg1;
+ (id)documentKey:(id)arg1;
+ (void)previewAndCommit:(id)arg1;
+ (void)toggleOverlayForDocument:(id)arg1;
+ (void)loadBeltForDocument:(id)arg1 metadata:(id)arg2;
+ (void)loadBeltForDocument:(id)arg1;
+ (void)startup;
+ (void)resumeSaveAbstractVersion;
+ (void)pauseSaveAbstractVersion;
+ (id)commander;
+ (id)pluginCommand;
+ (id)saveAbstractVersionOperationQueue;
+ (id)saveAbstractVersionHandlerQueue;
+ (id)openDocumentActionHandlerQueue;
+ (id)bootstrapQueue;
+ (id)registeredBootstraps;
+ (id)bootstrapRegistry;
@property(retain, nonatomic) NSMutableArray *saveOps; // @synthesize saveOps=_saveOps;
@property(nonatomic) NSTimer *isCommittingTimer; // @synthesize isCommittingTimer=_isCommittingTimer;
@property(retain, nonatomic) PROFloatingWindowController *floatingWindowController; // @synthesize floatingWindowController=_floatingWindowController;
@property(nonatomic) long long saveCount; // @synthesize saveCount=_saveCount;
@property(retain, nonatomic) SketchDocumentFilePresenter *filePresenter; // @synthesize filePresenter=_filePresenter;
@property(retain, nonatomic) id documentKey; // @synthesize documentKey=_documentKey;
@property(retain, nonatomic) PROSketchAbstractMetadata *abstractMetadata; // @synthesize abstractMetadata=_abstractMetadata;
@property(nonatomic) __weak MSDocument *document; // @synthesize document=_document;
- (void).cxx_destruct;
- (void)processSave:(BOOL)arg1 isTerminating:(BOOL)arg2;
- (void)enqueueSave:(BOOL)arg1 isTerminating:(BOOL)arg2;
- (void)startSavingSketchDocument;
- (void)dealloc;
- (void)teardown:(CDUnknownBlockType)arg1;
- (void)handleCloseNotification:(id)arg1;
- (void)addToSketchWindow;
- (void)clearIsCommitting;
- (void)setIsCommitting;
- (BOOL)isCommitting;
- (void)notifyCommit:(id)arg1 branchId:(id)arg2 status:(id)arg3 fileIds:(id)arg4;
- (id)commander;
- (id)pluginCommand;

@end

