//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSDocument, NSDictionary, NSMutableDictionary, NSString, PROSketchObjectGraphUtils;

@interface PROSketchFileDisassembler : NSObject
{
    MSDocument *_sketchDocument;
    NSString *_name;
    NSString *_identifier;
    NSDictionary *_appMetadata;
    NSDictionary *_projectLibraries;
    NSMutableDictionary *_manifestLibraries;
    PROSketchObjectGraphUtils *_objectGraphUtils;
}

@property(retain, nonatomic) PROSketchObjectGraphUtils *objectGraphUtils; // @synthesize objectGraphUtils=_objectGraphUtils;
@property(retain, nonatomic) NSMutableDictionary *manifestLibraries; // @synthesize manifestLibraries=_manifestLibraries;
@property(retain, nonatomic) NSDictionary *projectLibraries; // @synthesize projectLibraries=_projectLibraries;
@property(retain, nonatomic) NSDictionary *appMetadata; // @synthesize appMetadata=_appMetadata;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) MSDocument *sketchDocument; // @synthesize sketchDocument=_sketchDocument;
- (void).cxx_destruct;
- (id)addModel:(id)arg1 toDrawingCollection:(id)arg2 type:(id)arg3 name:(id)arg4 identifier:(id)arg5;
- (id)addModel:(id)arg1 toDrawingCollection:(id)arg2 type:(id)arg3 name:(id)arg4;
- (id)objectId:(id)arg1;
- (void)indexSharedStylesInLayer:(id)arg1 drawing:(id)arg2 rootIdentifier:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (id)createSharedInstanceIndex:(id)arg1;
- (void)addSharedDataToManifest:(id)arg1;
- (void)addSharedObjects:(id)arg1 withKey:(id)arg2 toManfestInFile:(id)arg3;
- (void)slimLayers:(id)arg1;
- (void)extractPagesAndLayers:(id)arg1 toFile:(id)arg2;
- (void)extractForeignSymbols:(id)arg1 toFile:(id)arg2;
- (void)addSharedData:(id)arg1 key:(id)arg2 type:(id)arg3 toFile:(id)arg4;
- (id)sharedObjectId:(id)arg1;
- (void)removeSharedObjectData:(id)arg1;
- (void)removeSharedObjectData:(id)arg1 skipIdCheck:(BOOL)arg2 additionalWhiteList:(id)arg3;
- (void)setLibraryStyleItemMeta:(id)arg1 libraryMetaKey:(id)arg2;
- (id)manifestLibraryRefCollection:(id)arg1 key:(id)arg2;
- (id)sharedDataCollection:(id)arg1 key:(id)arg2;
- (void)extractForeignStyles:(id)arg1 toFile:(id)arg2 sketchCollectionKey:(id)arg3 abstractCollectionKey:(id)arg4 key:(id)arg5 type:(id)arg6;
- (void)extractForeignTextStyles:(id)arg1 toFile:(id)arg2;
- (void)extractForeignLayerStyles:(id)arg1 toFile:(id)arg2;
- (void)extractTextStyles:(id)arg1 toFile:(id)arg2;
- (void)extractSymbols:(id)arg1 toFile:(id)arg2;
- (void)extractLayerStyles:(id)arg1 toFile:(id)arg2;
- (void)extractAssetsCollection:(id)arg1 toFile:(id)arg2;
- (id)infoWithIdentifier:(id)arg1 name:(id)arg2;
- (BOOL)addResourceTo:(id)arg1 fromResourceData:(id)arg2;
- (void)extractResourceFromDict:(id)arg1 toResources:(id)arg2;
- (void)extractResourcesFromLayer:(id)arg1 toResources:(id)arg2;
- (id)extractResources:(id)arg1 toFile:(id)arg2;
- (id)extractUserPreferences:(id)arg1 uiMetadata:(id)arg2 identifier:(id)arg3;
- (void)extractDocumentData:(id)arg1 toFile:(id)arg2;
- (id)createDrawing;
- (id)initWithDocument:(id)arg1 name:(id)arg2 identifier:(id)arg3 libraries:(id)arg4;

@end

