//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PROSketchArchivingService : NSObject
{
}

+ (id)allSketchClasses;
+ (void)defineReplacementClasses:(double)arg1;
+ (id)unarchiveModelObjectFromObjectGraph:(id)arg1 applicationVersion:(id)arg2 build:(id)arg3;
+ (id)archiveNonModelObject:(id)arg1;
+ (id)archiveDataGraphFromObject:(id)arg1;
+ (id)archiveModelObject:(id)arg1;
+ (id)normalizedModelObject:(id)arg1;
+ (id)archiveModelObjectGraph:(id)arg1;

@end

