//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString, PROAbstractConfig, PROAbstractMessageServer, PROSketchLibraryManager, PROSketchURLManager;

@interface PROSketchPluginManager : NSObject
{
    BOOL _needsRestart;
    int _sketchMajorVersion;
    int _sketchBuildNumber;
    int _abstractPluginBuildNumber;
    NSString *_sketchBundleID;
    NSString *_sketchVersion;
    NSObject<OS_dispatch_semaphore> *_concurrencyLimitSemaphore;
    NSObject<OS_dispatch_queue> *_processingQueue;
    NSObject<OS_dispatch_queue> *_controlQueue;
    NSObject<OS_dispatch_queue> *_previewQueue;
    PROAbstractMessageServer *_messageServer;
    PROSketchLibraryManager *_libraryManager;
    PROSketchURLManager *_urlManager;
    PROAbstractConfig *_config;
}

+ (void)configurePlugin:(id)arg1;
+ (void)safeTerminate;
+ (void)restartSketch;
+ (void)unregisterActiveMetadata:(id)arg1;
+ (void)registerActiveMetadata:(id)arg1;
+ (void)removeLibrariesForMetadata:(id)arg1;
+ (void)addLibrariesForMetadata:(id)arg1;
+ (void)saveAbstractFile:(id)arg1 url:(id)arg2 abstractMetadata:(id)arg3 isTerminating:(BOOL)arg4 finished:(CDUnknownBlockType)arg5;
+ (id)config;
+ (id)libraryManager;
+ (id)urlManager;
+ (id)pluginManager;
@property(nonatomic) BOOL needsRestart; // @synthesize needsRestart=_needsRestart;
@property(retain, nonatomic) PROAbstractConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) PROSketchURLManager *urlManager; // @synthesize urlManager=_urlManager;
@property(retain, nonatomic) PROSketchLibraryManager *libraryManager; // @synthesize libraryManager=_libraryManager;
@property(retain, nonatomic) PROAbstractMessageServer *messageServer; // @synthesize messageServer=_messageServer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *previewQueue; // @synthesize previewQueue=_previewQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *controlQueue; // @synthesize controlQueue=_controlQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *processingQueue; // @synthesize processingQueue=_processingQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *concurrencyLimitSemaphore; // @synthesize concurrencyLimitSemaphore=_concurrencyLimitSemaphore;
@property(nonatomic) int abstractPluginBuildNumber; // @synthesize abstractPluginBuildNumber=_abstractPluginBuildNumber;
@property(nonatomic) int sketchBuildNumber; // @synthesize sketchBuildNumber=_sketchBuildNumber;
@property(nonatomic) int sketchMajorVersion; // @synthesize sketchMajorVersion=_sketchMajorVersion;
@property(nonatomic) NSString *sketchVersion; // @synthesize sketchVersion=_sketchVersion;
@property(nonatomic) NSString *sketchBundleID; // @synthesize sketchBundleID=_sketchBundleID;
- (void).cxx_destruct;
- (id)fileWrapperForSHA:(id)arg1 abstractFileURL:(id)arg2;
- (id)drawingFromDocument:(id)arg1 identifier:(id)arg2 name:(id)arg3 libraries:(id)arg4;
- (id)drawingFromDocument:(id)arg1 name:(id)arg2 libraries:(id)arg3;
- (void)saveOpenFilesWithMessage:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (void)listOpenFilesWithMessage:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (void)notifyCommitWithMessage:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (void)upgradeSketchFilesWithMessage:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (id)readPropellerFile:(id)arg1;
- (void)focusDocumentLayerId:(id)arg1 layerId:(id)arg2;
- (void)openFilePathWithMessage:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (void)openAbstractFileWithMessage:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (void)exportAbstractFileWithMessage:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (void)closeSketchFilesWithMessage:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (id)exportLayer:(id)arg1 outputFormat:(id)arg2 doc:(id)arg3 docData:(id)arg4 page:(id)arg5 oldSchool:(BOOL)arg6 scale:(id)arg7;
- (void)exportLayers:(id)arg1 inDocument:(id)arg2 outputFormat:(id)arg3 scale:(id)arg4 progress:(CDUnknownBlockType)arg5 completion:(CDUnknownBlockType)arg6;
- (void)generatePreviews:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (void)exportBitmaps:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (void)createAbstractFile:(id)arg1 progress:(CDUnknownBlockType)arg2;
- (void)startServer;
- (void)dealloc;
- (void)appWillTerminate:(id)arg1;
- (id)init;

@end

