//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PROJSONCoder.h"

@class NSArray, NSMutableSet, NSPointerArray;

@interface PROSketchCoder : PROJSONCoder
{
    NSMutableSet *_internalArchivedImages;
    NSArray *_actualSymbolIDs;
    id _legacyImages;
    SEL _propertyDecoder;
    long long _version;
    long long _archiveVersion;
    long long _currentVersion;
    NSPointerArray *__decodedObjectStack;
    id __currentDecodedObject;
}

+ (id)unarchiveGraphObject:(id)arg1 build:(id)arg2;
+ (id)archiveRootObject:(id)arg1;
+ (id)archivedDataWithRootObject:(id)arg1;
@property(nonatomic) __weak id _currentDecodedObject; // @synthesize _currentDecodedObject=__currentDecodedObject;
@property(retain, nonatomic) NSPointerArray *_decodedObjectStack; // @synthesize _decodedObjectStack=__decodedObjectStack;
@property(nonatomic) long long currentVersion; // @synthesize currentVersion=_currentVersion;
@property(nonatomic) long long archiveVersion; // @synthesize archiveVersion=_archiveVersion;
@property(nonatomic) long long version; // @synthesize version=_version;
@property(nonatomic) SEL propertyDecoder; // @synthesize propertyDecoder=_propertyDecoder;
@property(retain, nonatomic) id legacyImages; // @synthesize legacyImages=_legacyImages;
@property(retain, nonatomic) NSArray *actualSymbolIDs; // @synthesize actualSymbolIDs=_actualSymbolIDs;
@property(retain, nonatomic) NSMutableSet *internalArchivedImages; // @synthesize internalArchivedImages=_internalArchivedImages;
- (void).cxx_destruct;
- (BOOL)unarchiveNumberKeysAsStrings;
- (id)currentObject;
- (void)setCurrentObject:(id)arg1;
- (void)setDecodedObjectStack:(id)arg1;
- (id)decodedObjectStack;
- (id)instanciateObject:(id)arg1;
- (id)unarchiver;
- (id)archiver;
@property(readonly, nonatomic) NSMutableSet *archivedImages;
@property(readonly, nonatomic) BOOL archiveObjectIDs;

@end

