//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "OTSpanContext.h"

@class NSDictionary;

@interface PROSpanContext : NSObject <OTSpanContext>
{
    unsigned char _flags;
    unsigned long long _traceId;
    unsigned long long _spanId;
    unsigned long long _parentId;
    NSDictionary *_baggage;
}

+ (id)fromString:(id)arg1;
@property(readonly, nonatomic) NSDictionary *baggage; // @synthesize baggage=_baggage;
@property(readonly, nonatomic) unsigned char flags; // @synthesize flags=_flags;
@property(readonly, nonatomic) unsigned long long parentId; // @synthesize parentId=_parentId;
@property(readonly, nonatomic) unsigned long long spanId; // @synthesize spanId=_spanId;
@property(readonly, nonatomic) unsigned long long traceId; // @synthesize traceId=_traceId;
- (void).cxx_destruct;
- (void)forEachBaggageItem:(CDUnknownBlockType)arg1;
- (id)description;
- (id)initWithParent:(id)arg1;
- (id)initWithBaggage:(id)arg1;
- (id)initWithTraceId:(unsigned long long)arg1 spanId:(unsigned long long)arg2 parentId:(unsigned long long)arg3 flags:(unsigned char)arg4 baggage:(id)arg5;
- (id)init;

@end

