//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSPluginCommand;

@interface PROSketchCommander : NSObject
{
    MSPluginCommand *_command;
}

@property(retain, nonatomic) MSPluginCommand *command; // @synthesize command=_command;
- (void).cxx_destruct;
- (id)pluginIdentifier;
- (id)findLayerWithPersistentIdentifier:(id)arg1 rootLayer:(id)arg2;
- (id)valueForKey:(id)arg1 onDocument:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2 onDocument:(id)arg3;
- (id)valueForKey:(id)arg1 onLayer:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2 onLayer:(id)arg3;
- (id)rootLayerNeedingReplacementPersistentIdentifier:(id)arg1;
- (BOOL)layerNeedsReplacingPersistentIdentifier:(id)arg1;
- (id)fetchPersistentIdentifier:(id)arg1;
- (id)assignPersistentIdentifier:(id)arg1 override:(BOOL)arg2;
- (id)assignPersistentIdentifier:(id)arg1;
- (void)assignPersistentIdentifiersToTree:(id)arg1;
- (id)initWithCommand:(id)arg1;

@end

