//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSAssetLibraryController, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSTimer;

@interface PROSketchLibraryManager : NSObject
{
    MSAssetLibraryController *_sketchLibrariesController;
    NSObject<OS_dispatch_queue> *_libraryControlQueue;
    NSObject<OS_dispatch_queue> *_libraryLoadQueue;
    NSMutableDictionary *_openFilesByBranch;
    NSMutableDictionary *_branchesUsingLibrarySha;
    NSMutableDictionary *_libraryShasByBranchId;
    NSMutableDictionary *_cachedLibrariesBySha;
    NSTimer *_notifyTimer;
}

+ (id)repoUrl:(id)arg1;
+ (id)reposUrl;
+ (id)documentsUrl;
+ (id)abstractSupportUrl;
+ (id)metadataForLibraryRef:(id)arg1 activeFileMeta:(id)arg2;
@property(retain, nonatomic) NSTimer *notifyTimer; // @synthesize notifyTimer=_notifyTimer;
@property(retain, nonatomic) NSMutableDictionary *cachedLibrariesBySha; // @synthesize cachedLibrariesBySha=_cachedLibrariesBySha;
@property(retain, nonatomic) NSMutableDictionary *libraryShasByBranchId; // @synthesize libraryShasByBranchId=_libraryShasByBranchId;
@property(retain, nonatomic) NSMutableDictionary *branchesUsingLibrarySha; // @synthesize branchesUsingLibrarySha=_branchesUsingLibrarySha;
@property(retain, nonatomic) NSMutableDictionary *openFilesByBranch; // @synthesize openFilesByBranch=_openFilesByBranch;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *libraryLoadQueue; // @synthesize libraryLoadQueue=_libraryLoadQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *libraryControlQueue; // @synthesize libraryControlQueue=_libraryControlQueue;
@property(retain, nonatomic) MSAssetLibraryController *sketchLibrariesController; // @synthesize sketchLibrariesController=_sketchLibrariesController;
- (void).cxx_destruct;
- (void)loadLibraryAsyncWithCompletion:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)cacheKey:(id)arg1;
- (BOOL)libraryIsTracked:(id)arg1;
- (void)removeAllAbstractLibraries;
- (void)_notifyLibraryChanges;
- (void)notifyLibraryChanges;
- (void)libraryLoaded:(id)arg1 withMeta:(id)arg2 forBranchId:(id)arg3;
- (void)loadLibraryAtUrl:(id)arg1 forBranchId:(id)arg2 withMeta:(id)arg3;
- (void)unregisterActiveMetadata:(id)arg1;
- (void)registerActiveMetadata:(id)arg1;
- (void)removeLibrariesForMetadata:(id)arg1;
- (void)addLibrariesForMetadata:(id)arg1;
- (id)openLibrariesByBranchId:(id)arg1;
- (void)reloadLibrariesPreferencePane;
- (id)init;

@end

