//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PROTag : NSObject
{
    NSString *_key;
    NSObject *_value;
    long long _type;
}

@property(readonly, nonatomic) long long type; // @synthesize type=_type;
@property(readonly, nonatomic) NSObject *value; // @synthesize value=_value;
@property(readonly, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (id)toRPC;
- (id)initWithData:(id)arg1 key:(id)arg2;
- (id)initWithBool:(BOOL)arg1 key:(id)arg2;
- (id)initWithDouble:(double)arg1 key:(id)arg2;
- (id)initWithLong:(long long)arg1 key:(id)arg2;
- (id)initWithString:(id)arg1 key:(id)arg2;

@end

