//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "OTTracer.h"

@class NSMutableArray, NSMutableDictionary, PROAbstractConfig, PROSketchURLManager;

@interface PROTracer : NSObject <OTTracer>
{
    BOOL _enabled;
    PROAbstractConfig *_config;
    PROSketchURLManager *_urlManager;
    NSMutableArray *_reporters;
    NSMutableDictionary *_baggage;
}

@property(retain, nonatomic) NSMutableDictionary *baggage; // @synthesize baggage=_baggage;
@property(retain, nonatomic) NSMutableArray *reporters; // @synthesize reporters=_reporters;
@property(retain, nonatomic) PROSketchURLManager *urlManager; // @synthesize urlManager=_urlManager;
@property(retain, nonatomic) PROAbstractConfig *config; // @synthesize config=_config;
@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
- (id)setBaggageItem:(id)arg1 key:(id)arg2 value:(id)arg3;
- (id)baggageItem:(id)arg1;
- (void)reportSpan:(id)arg1;
- (id)extractWithFormat:(id)arg1 carrier:(id)arg2 error:(id *)arg3;
- (id)extractWithFormat:(id)arg1 carrier:(id)arg2;
- (BOOL)inject:(id)arg1 format:(id)arg2 carrier:(id)arg3 error:(id *)arg4;
- (BOOL)inject:(id)arg1 format:(id)arg2 carrier:(id)arg3;
- (id)startSpan:(id)arg1 references:(id)arg2 tags:(id)arg3 startTime:(id)arg4;
- (id)startSpan:(id)arg1 childOf:(id)arg2 tags:(id)arg3 startTime:(id)arg4;
- (id)startSpan:(id)arg1 childOf:(id)arg2 tags:(id)arg3;
- (id)startSpan:(id)arg1 childOf:(id)arg2;
- (id)startSpan:(id)arg1 tags:(id)arg2;
- (id)startSpan:(id)arg1;
- (id)initWithConfig:(id)arg1 urlManager:(id)arg2;

@end

