//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSFilePresenter.h"

@class MSDocument, NSOperationQueue, NSSet, NSString, NSURL, PROSketchBootstrap;

@interface SketchDocumentFilePresenter : NSObject <NSFilePresenter>
{
    BOOL _stopShowingUntrackedFileWarning;
    PROSketchBootstrap *_bootstrap;
    MSDocument *_sketchDocument;
    NSString *_savePath;
    NSOperationQueue *_processingQueue;
}

+ (void)appWillTerminate:(id)arg1;
+ (void)initialize;
+ (id)saveGroup;
@property(retain, nonatomic) NSOperationQueue *processingQueue; // @synthesize processingQueue=_processingQueue;
@property(copy, nonatomic) NSString *savePath; // @synthesize savePath=_savePath;
@property(retain, nonatomic) MSDocument *sketchDocument; // @synthesize sketchDocument=_sketchDocument;
@property(nonatomic) __weak PROSketchBootstrap *bootstrap; // @synthesize bootstrap=_bootstrap;
@property(nonatomic) BOOL stopShowingUntrackedFileWarning; // @synthesize stopShowingUntrackedFileWarning=_stopShowingUntrackedFileWarning;
- (void).cxx_destruct;
- (void)accommodatePresentedItemDeletionWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)presentedItemDidChange;
- (void)relinquishPresentedItemToWriter:(CDUnknownBlockType)arg1;
- (void)relinquishPresentedItemToReader:(CDUnknownBlockType)arg1;
@property(readonly, retain) NSOperationQueue *presentedItemOperationQueue;
@property(readonly, copy) NSURL *presentedItemURL;
- (void)dealloc;
- (void)teardown;
- (id)initWithSketchDocument:(id)arg1 bootstrap:(id)arg2 savePath:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) NSSet *observedPresentedItemUbiquityAttributes;
@property(readonly, copy) NSURL *primaryPresentedItemURL;
@property(readonly) Class superclass;

@end

