//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct git_blame_hunk {
    unsigned long long lines_in_hunk;
    struct git_oid final_commit_id;
    unsigned long long final_start_line_number;
    struct git_signature *final_signature;
    struct git_oid orig_commit_id;
    char *orig_path;
    unsigned long long orig_start_line_number;
    struct git_signature *orig_signature;
    char boundary;
};

struct git_checkout_options {
    unsigned int version;
    unsigned int checkout_strategy;
    int disable_filters;
    unsigned int dir_mode;
    unsigned int file_mode;
    int file_open_flags;
    unsigned int notify_flags;
    CDUnknownFunctionPointerType notify_cb;
    void *notify_payload;
    CDUnknownFunctionPointerType progress_cb;
    void *progress_payload;
    struct git_strarray paths;
    struct git_tree *baseline;
    struct git_index *baseline_index;
    char *target_directory;
    char *ancestor_label;
    char *our_label;
    char *their_label;
    CDUnknownFunctionPointerType perfdata_cb;
    void *perfdata_payload;
};

struct git_cred {
    int _field1;
    CDUnknownFunctionPointerType _field2;
};

struct git_filter {
    unsigned int version;
    char *attributes;
    CDUnknownFunctionPointerType initialize;
    CDUnknownFunctionPointerType shutdown;
    CDUnknownFunctionPointerType check;
    CDUnknownFunctionPointerType apply;
    CDUnknownFunctionPointerType stream;
    CDUnknownFunctionPointerType cleanup;
};

struct git_index;

struct git_index_entry {
    CDStruct_f1d50d6b _field1;
    CDStruct_f1d50d6b _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
    struct git_oid _field9;
    unsigned short _field10;
    unsigned short _field11;
    char *_field12;
};

struct git_oid {
    unsigned char id[20];
};

struct git_signature {
    char *_field1;
    char *_field2;
    struct git_time _field3;
};

struct git_strarray {
    char **strings;
    unsigned long long count;
};

struct git_time {
    long long _field1;
    int _field2;
    char _field3;
};

struct git_tree;

#pragma mark Typedef'd Structures

typedef struct {
    char *_field1;
    unsigned long long _field2;
    unsigned long long _field3;
} CDStruct_8bf61218;

typedef struct {
    char _field1;
    int _field2;
    int _field3;
    int _field4;
    unsigned long long _field5;
    long long _field6;
    char *_field7;
} CDStruct_27b4a69e;

typedef struct {
    int _field1;
    unsigned int _field2;
} CDStruct_f1d50d6b;

typedef struct {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    unsigned long long _field5;
    char _field6[128];
} CDStruct_f0d88aad;

typedef struct {
    unsigned int _field1;
    unsigned int _field2;
    unsigned short _field3;
    unsigned short _field4;
    unsigned short _field5;
    unsigned short _field6;
    unsigned long long _field7;
    struct *_field8;
} CDStruct_69e0e667;

typedef struct {
    struct git_oid id;
    char *path;
    long long size;
    unsigned int flags;
    unsigned short mode;
    unsigned short id_abbrev;
} CDStruct_95e4261d;

typedef struct {
    int _field1;
    unsigned int _field2;
    unsigned short _field3;
    unsigned short _field4;
    CDStruct_95e4261d _field5;
    CDStruct_95e4261d _field6;
} CDStruct_10a53f2e;

