//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, GTSignature, NSString;

@interface GTBlameHunk : NSObject
{
    struct git_blame_hunk _git_blame_hunk;
}

@property(readonly, nonatomic) struct git_blame_hunk git_blame_hunk; // @synthesize git_blame_hunk=_git_blame_hunk;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic, getter=isBoundary) BOOL boundary;
@property(readonly, copy, nonatomic) NSString *originalPath;
@property(readonly, nonatomic) GTSignature *finalSignature;
@property(readonly, copy, nonatomic) GTOID *finalCommitOID;
@property(readonly, nonatomic) struct _NSRange lines;
- (id)initWithGitBlameHunk:(struct git_blame_hunk)arg1;
- (id)init;

@end

