//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ObjectiveGit/GTObject.h>

@interface GTBlob : GTObject
{
}

+ (id)blobWithFile:(id)arg1 inRepository:(id)arg2 error:(id *)arg3;
+ (id)blobWithData:(id)arg1 inRepository:(id)arg2 error:(id *)arg3;
+ (id)blobWithString:(id)arg1 inRepository:(id)arg2 error:(id *)arg3;
- (id)applyFiltersForPath:(id)arg1 error:(id *)arg2;
- (id)data;
- (id)content;
- (long long)size;
- (struct git_blob *)git_blob;
- (id)initWithFile:(id)arg1 inRepository:(id)arg2 error:(id *)arg3;
- (id)initWithData:(id)arg1 inRepository:(id)arg2 error:(id *)arg3;
- (id)initWithString:(id)arg1 inRepository:(id)arg2 error:(id *)arg3;
- (id)initWithOid:(const struct git_oid *)arg1 inRepository:(id)arg2 error:(id *)arg3;
- (id)description;

@end

