//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface GTBlame : NSObject
{
    struct git_blame *_git_blame;
}

@property(readonly, nonatomic) struct git_blame *git_blame; // @synthesize git_blame=_git_blame;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)hunkAtLineNumber:(unsigned long long)arg1;
@property(readonly, nonatomic) NSArray *hunks;
- (void)enumerateHunksUsingBlock:(CDUnknownBlockType)arg1;
- (id)hunkAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long hunkCount;
- (void)dealloc;
- (id)initWithGitBlame:(struct git_blame *)arg1;
- (id)init;

@end

