//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, GTReference, GTRepository, NSString;

@interface GTBranch : NSObject
{
    GTReference *_reference;
}

+ (id)branchWithReference:(id)arg1;
+ (id)remoteNamePrefix;
+ (id)localNamePrefix;
@property(readonly, nonatomic) GTReference *reference; // @synthesize reference=_reference;
- (void).cxx_destruct;
- (BOOL)calculateAhead:(unsigned long long *)arg1 behind:(unsigned long long *)arg2 relativeTo:(id)arg3 error:(id *)arg4;
- (id)reloadedBranchWithError:(id *)arg1;
- (BOOL)updateTrackingBranch:(id)arg1 error:(id *)arg2;
- (id)trackingBranchWithError:(id *)arg1 success:(char *)arg2;
- (BOOL)rename:(id)arg1 force:(BOOL)arg2 error:(id *)arg3;
- (BOOL)deleteWithError:(id *)arg1;
- (id)uniqueCommitsRelativeToBranch:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic, getter=isHEAD) BOOL HEAD;
@property(readonly, nonatomic) long long branchType;
@property(readonly, nonatomic) GTRepository *repository;
- (unsigned long long)numberOfCommitsWithError:(id *)arg1;
- (id)targetCommitWithError:(id *)arg1;
@property(readonly, nonatomic) NSString *remoteName;
@property(readonly, copy, nonatomic) GTOID *OID;
@property(readonly, nonatomic) NSString *shortName;
@property(readonly, nonatomic) NSString *name;
- (id)initWithReference:(id)arg1;
- (id)init;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;

@end

