//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface GTCheckoutOptions : NSObject
{
    struct git_checkout_options _git_checkoutOptions;
    long long _strategy;
    CDUnknownBlockType _progressBlock;
    long long _notifyFlags;
    CDUnknownBlockType _notifyBlock;
    NSArray *_pathSpecs;
}

+ (id)checkoutOptionsWithStrategy:(long long)arg1;
+ (id)checkoutOptionsWithStrategy:(long long)arg1 notifyFlags:(long long)arg2 notifyBlock:(CDUnknownBlockType)arg3;
+ (id)checkoutOptionsWithStrategy:(long long)arg1 progressBlock:(CDUnknownBlockType)arg2;
+ (id)checkoutOptionsWithStrategy:(long long)arg1 notifyFlags:(long long)arg2 progressBlock:(CDUnknownBlockType)arg3 notifyBlock:(CDUnknownBlockType)arg4;
@property(copy) NSArray *pathSpecs; // @synthesize pathSpecs=_pathSpecs;
@property(copy) CDUnknownBlockType notifyBlock; // @synthesize notifyBlock=_notifyBlock;
@property long long notifyFlags; // @synthesize notifyFlags=_notifyFlags;
@property(copy) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property long long strategy; // @synthesize strategy=_strategy;
- (void).cxx_destruct;
- (struct git_checkout_options *)git_checkoutOptions;
- (id)init;

@end

