//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTRepository, NSArray;

@interface GTConfiguration : NSObject
{
    GTRepository *_repository;
    struct git_config *_git_config;
}

+ (id)defaultConfiguration;
@property(readonly, nonatomic) struct git_config *git_config; // @synthesize git_config=_git_config;
@property(readonly, nonatomic) GTRepository *repository; // @synthesize repository=_repository;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *remotes;
@property(readonly, copy, nonatomic) NSArray *configurationKeys;
- (BOOL)deleteValueForKey:(id)arg1 error:(id *)arg2;
- (long long)int64ForKey:(id)arg1;
- (void)setInt64:(long long)arg1 forKey:(id)arg2;
- (int)int32ForKey:(id)arg1;
- (void)setInt32:(int)arg1 forKey:(id)arg2;
- (BOOL)boolForKey:(id)arg1;
- (void)setBool:(BOOL)arg1 forKey:(id)arg2;
- (id)stringForKey:(id)arg1;
- (void)setString:(id)arg1 forKey:(id)arg2;
- (id)initWithGitConfig:(struct git_config *)arg1 repository:(id)arg2;
- (id)init;
- (void)dealloc;

@end

