//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ObjectiveGit/GTObject.h>

@class GTOID, GTSignature, GTTree, NSArray, NSDate, NSString, NSTimeZone;

@interface GTCommit : GTObject
{
}

- (id)merge:(id)arg1 error:(id *)arg2;
@property(readonly, copy, nonatomic) NSArray *parents;
@property(readonly, copy, nonatomic) NSArray *parentOIDs;
@property(readonly, nonatomic, getter=isMerge) BOOL merge;
@property(readonly, nonatomic) GTTree *tree;
@property(readonly, nonatomic) GTSignature *committer;
@property(readonly, nonatomic) GTSignature *author;
@property(readonly, nonatomic) NSTimeZone *commitTimeZone;
@property(readonly, nonatomic) NSDate *commitDate;
- (struct git_time)commitTime;
@property(readonly, nonatomic) NSString *messageSummary;
@property(readonly, nonatomic) NSString *messageDetails;
@property(readonly, nonatomic) NSString *message;
@property(readonly, nonatomic) GTOID *OID;
- (struct git_commit *)git_commit;
- (id)description;

@end

