//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GTCredential : NSObject
{
    struct git_cred *_git_cred;
}

+ (id)credentialWithUserName:(id)arg1 publicKeyString:(id)arg2 privateKeyString:(id)arg3 passphrase:(id)arg4 error:(id *)arg5;
+ (id)credentialWithUserName:(id)arg1 publicKeyURL:(id)arg2 privateKeyURL:(id)arg3 passphrase:(id)arg4 error:(id *)arg5;
+ (id)credentialWithUserName:(id)arg1 password:(id)arg2 error:(id *)arg3;
@property(readonly, nonatomic) struct git_cred *git_cred; // @synthesize git_cred=_git_cred;
- (id)initWithGitCred:(struct git_cred *)arg1;

@end

