//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTRepository;

@interface GTDiff : NSObject
{
    struct git_diff *_git_diff;
    GTRepository *_repository;
}

+ (id)diffWorkingDirectoryToHEADInRepository:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (id)diffWorkingDirectoryFromTree:(id)arg1 inRepository:(id)arg2 options:(id)arg3 error:(id *)arg4;
+ (id)diffIndexToWorkingDirectoryInRepository:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (id)diffIndexFromTree:(id)arg1 inRepository:(id)arg2 options:(id)arg3 error:(id *)arg4;
+ (id)diffOldIndex:(id)arg1 withNewIndex:(id)arg2 inRepository:(id)arg3 options:(id)arg4 error:(id *)arg5;
+ (id)diffOldTree:(id)arg1 withNewIndex:(id)arg2 inRepository:(id)arg3 options:(id)arg4 error:(id *)arg5;
+ (id)diffOldTree:(id)arg1 withNewTree:(id)arg2 inRepository:(id)arg3 options:(id)arg4 error:(id *)arg5;
+ (int)handleParsedOptionsDictionary:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) GTRepository *repository; // @synthesize repository=_repository;
@property(readonly, nonatomic) struct git_diff *git_diff; // @synthesize git_diff=_git_diff;
- (void).cxx_destruct;
- (BOOL)mergeDiffWithDiff:(id)arg1 error:(id *)arg2;
- (void)findSimilarWithOptions:(id)arg1;
- (BOOL)findOptionsStructWithDictionary:(id)arg1 optionsStruct:(CDStruct_69e0e667 *)arg2;
- (unsigned long long)numberOfDeltasWithType:(long long)arg1;
@property(readonly, nonatomic) unsigned long long deltaCount;
- (void)enumerateDeltasUsingBlock:(CDUnknownBlockType)arg1;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithGitDiff:(struct git_diff *)arg1 repository:(id)arg2;
- (id)init;

@end

