//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GTDiffLine : NSObject
{
    BOOL _origin;
    NSString *_content;
    long long _oldLineNumber;
    long long _newLineNumber;
    long long _lineCount;
}

@property(readonly, nonatomic) long long lineCount; // @synthesize lineCount=_lineCount;
@property(readonly, nonatomic) BOOL origin; // @synthesize origin=_origin;
@property(readonly, nonatomic) long long newLineNumber; // @synthesize newLineNumber=_newLineNumber;
@property(readonly, nonatomic) long long oldLineNumber; // @synthesize oldLineNumber=_oldLineNumber;
@property(readonly, copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)initWithGitLine:(const CDStruct_27b4a69e *)arg1;
- (id)init;

@end

