//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTDiffDelta;

@interface GTDiffPatch : NSObject
{
    GTDiffDelta *_delta;
    unsigned long long _addedLinesCount;
    unsigned long long _deletedLinesCount;
    unsigned long long _contextLinesCount;
    struct git_patch *_git_patch;
}

@property(readonly, nonatomic) struct git_patch *git_patch; // @synthesize git_patch=_git_patch;
@property(readonly, nonatomic) unsigned long long contextLinesCount; // @synthesize contextLinesCount=_contextLinesCount;
@property(readonly, nonatomic) unsigned long long deletedLinesCount; // @synthesize deletedLinesCount=_deletedLinesCount;
@property(readonly, nonatomic) unsigned long long addedLinesCount; // @synthesize addedLinesCount=_addedLinesCount;
@property(readonly, nonatomic) GTDiffDelta *delta; // @synthesize delta=_delta;
- (void).cxx_destruct;
- (BOOL)enumerateHunksUsingBlock:(CDUnknownBlockType)arg1;
- (id)patchData;
- (unsigned long long)sizeWithContext:(BOOL)arg1 hunkHeaders:(BOOL)arg2 fileHeaders:(BOOL)arg3;
@property(readonly, nonatomic) unsigned long long hunkCount;
- (void)dealloc;
- (id)initWithGitPatch:(struct git_patch *)arg1 delta:(id)arg2;
- (id)init;

@end

