//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTDiffFile;

@interface GTDiffDelta : NSObject
{
    CDUnknownBlockType _deltaAccessor;
    CDUnknownBlockType _patchGenerator;
}

+ (id)diffDeltaFromData:(id)arg1 forPath:(id)arg2 toData:(id)arg3 forPath:(id)arg4 options:(id)arg5 error:(id *)arg6;
+ (id)diffDeltaFromBlob:(id)arg1 forPath:(id)arg2 toData:(id)arg3 forPath:(id)arg4 options:(id)arg5 error:(id *)arg6;
+ (id)diffDeltaFromBlob:(id)arg1 forPath:(id)arg2 toBlob:(id)arg3 forPath:(id)arg4 options:(id)arg5 error:(id *)arg6;
@property(readonly, copy, nonatomic) CDUnknownBlockType patchGenerator; // @synthesize patchGenerator=_patchGenerator;
@property(readonly, copy, nonatomic) CDUnknownBlockType deltaAccessor; // @synthesize deltaAccessor=_deltaAccessor;
- (void).cxx_destruct;
- (id)description;
- (id)generatePatch:(id *)arg1;
- (id)initWithGitDiffDeltaBlock:(CDUnknownBlockType)arg1 patchGeneratorBlock:(CDUnknownBlockType)arg2;
- (id)initWithDiff:(id)arg1 deltaIndex:(unsigned long long)arg2;
- (id)init;
@property(readonly, nonatomic) double similarity;
@property(readonly, nonatomic) long long type;
@property(readonly, copy, nonatomic) GTDiffFile *newFile;
@property(readonly, copy, nonatomic) GTDiffFile *oldFile;
@property(readonly, nonatomic) long long flags;
@property(readonly, nonatomic) CDStruct_10a53f2e git_diff_delta;

@end

