//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTDiffPatch, NSString;

@interface GTDiffHunk : NSObject
{
    NSString *_header;
    unsigned long long _lineCount;
    unsigned long long _oldStart;
    unsigned long long _oldLines;
    unsigned long long _newStart;
    unsigned long long _newLines;
    const CDStruct_f0d88aad *_git_hunk;
    GTDiffPatch *_patch;
    unsigned long long _hunkIndex;
}

@property(readonly, nonatomic) unsigned long long hunkIndex; // @synthesize hunkIndex=_hunkIndex;
@property(readonly, nonatomic) GTDiffPatch *patch; // @synthesize patch=_patch;
@property(readonly, nonatomic) const CDStruct_f0d88aad *git_hunk; // @synthesize git_hunk=_git_hunk;
@property(readonly, nonatomic) unsigned long long newLines; // @synthesize newLines=_newLines;
@property(readonly, nonatomic) unsigned long long newStart; // @synthesize newStart=_newStart;
@property(readonly, nonatomic) unsigned long long oldLines; // @synthesize oldLines=_oldLines;
@property(readonly, nonatomic) unsigned long long oldStart; // @synthesize oldStart=_oldStart;
@property(readonly, nonatomic) unsigned long long lineCount; // @synthesize lineCount=_lineCount;
@property(readonly, copy, nonatomic) NSString *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (BOOL)enumerateLinesInHunk:(id *)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)debugDescription;
- (id)initWithPatch:(id)arg1 hunkIndex:(unsigned long long)arg2;
- (id)init;

@end

