//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, NSString;

@interface GTDiffFile : NSObject
{
    unsigned short _mode;
    NSString *_path;
    unsigned long long _size;
    long long _flags;
    CDStruct_95e4261d _git_diff_file;
}

@property(readonly, nonatomic) CDStruct_95e4261d git_diff_file; // @synthesize git_diff_file=_git_diff_file;
@property(readonly, nonatomic) unsigned short mode; // @synthesize mode=_mode;
@property(readonly, nonatomic) long long flags; // @synthesize flags=_flags;
@property(readonly, nonatomic) unsigned long long size; // @synthesize size=_size;
@property(readonly, copy, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) GTOID *OID;
- (id)debugDescription;
- (id)initWithGitDiffFile:(CDStruct_95e4261d)arg1;
- (id)init;

@end

