//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, GTReference, NSString;

@interface GTFetchHeadEntry : NSObject
{
    BOOL _merge;
    GTReference *_reference;
    NSString *_remoteURLString;
    GTOID *_targetOID;
}

@property(readonly, nonatomic, getter=isMerge) BOOL merge; // @synthesize merge=_merge;
@property(readonly, copy, nonatomic) GTOID *targetOID; // @synthesize targetOID=_targetOID;
@property(readonly, copy, nonatomic) NSString *remoteURLString; // @synthesize remoteURLString=_remoteURLString;
@property(readonly, nonatomic) GTReference *reference; // @synthesize reference=_reference;
- (void).cxx_destruct;
- (id)description;
- (id)initWithReference:(id)arg1 remoteURLString:(id)arg2 targetOID:(id)arg3 isMerge:(BOOL)arg4;
- (id)init;

@end

