//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GTFilter : NSObject
{
    struct git_filter _filter;
    CDUnknownBlockType _initializeBlock;
    CDUnknownBlockType _shutdownBlock;
    CDUnknownBlockType _checkBlock;
    CDUnknownBlockType _cleanupBlock;
    NSString *_name;
    CDUnknownBlockType _applyBlock;
}

+ (id)filterForName:(id)arg1;
+ (void)initialize;
@property(readonly, copy, nonatomic) CDUnknownBlockType applyBlock; // @synthesize applyBlock=_applyBlock;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) CDUnknownBlockType cleanupBlock; // @synthesize cleanupBlock=_cleanupBlock;
@property(copy, nonatomic) CDUnknownBlockType checkBlock; // @synthesize checkBlock=_checkBlock;
@property(copy, nonatomic) CDUnknownBlockType shutdownBlock; // @synthesize shutdownBlock=_shutdownBlock;
@property(copy, nonatomic) CDUnknownBlockType initializeBlock; // @synthesize initializeBlock=_initializeBlock;
- (void).cxx_destruct;
- (BOOL)unregister:(id *)arg1;
- (BOOL)registerWithPriority:(int)arg1 error:(id *)arg2;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithName:(id)arg1 attributes:(id)arg2 applyBlock:(CDUnknownBlockType)arg3;
- (id)init;

@end

