//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, NSString, NSURL;

@interface GTFilterSource : NSObject
{
    NSURL *_repositoryURL;
    NSString *_path;
    GTOID *_OID;
    long long _mode;
}

@property(readonly, nonatomic) long long mode; // @synthesize mode=_mode;
@property(readonly, nonatomic) GTOID *OID; // @synthesize OID=_OID;
@property(readonly, copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(readonly, nonatomic) NSURL *repositoryURL; // @synthesize repositoryURL=_repositoryURL;
- (void).cxx_destruct;
- (id)initWithGitFilterSource:(const struct git_filter_source *)arg1;
- (id)init;

@end

