//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTRepository, NSArray, NSURL;

@interface GTIndex : NSObject
{
    GTRepository *_repository;
    struct git_index *_git_index;
}

+ (id)indexWithFileURL:(id)arg1 repository:(id)arg2 error:(id *)arg3;
+ (id)inMemoryIndexWithRepository:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) struct git_index *git_index; // @synthesize git_index=_git_index;
@property(readonly, nonatomic) GTRepository *repository; // @synthesize repository=_repository;
- (void).cxx_destruct;
- (id)entryWithName:(id)arg1 error:(id *)arg2;
- (id)entryWithName:(id)arg1;
- (id)composedUnicodeStringWithString:(id)arg1;
- (BOOL)updatePathspecs:(id)arg1 error:(id *)arg2 passingTest:(CDUnknownBlockType)arg3;
- (BOOL)enumerateConflictedFilesWithError:(id *)arg1 usingBlock:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) BOOL hasConflicts;
@property(readonly, copy, nonatomic) NSArray *entries;
- (id)writeTreeToRepository:(id)arg1 error:(id *)arg2;
- (id)writeTree:(id *)arg1;
- (BOOL)write:(id *)arg1;
- (BOOL)removeFile:(id)arg1 error:(id *)arg2;
- (BOOL)addAll:(id *)arg1;
- (BOOL)addContentsOfTree:(id)arg1 error:(id *)arg2;
- (BOOL)addData:(id)arg1 withPath:(id)arg2 error:(id *)arg3;
- (BOOL)addFile:(id)arg1 error:(id *)arg2;
- (BOOL)addEntry:(id)arg1 error:(id *)arg2;
- (id)entryWithPath:(id)arg1 error:(id *)arg2;
- (id)entryWithPath:(id)arg1;
- (id)entryAtIndex:(unsigned long long)arg1;
- (BOOL)clear:(id *)arg1;
- (BOOL)refresh:(id *)arg1;
@property(readonly, nonatomic) unsigned long long entryCount;
- (id)initWithGitIndex:(struct git_index *)arg1 repository:(id)arg2;
- (id)init;
- (void)dealloc;
- (id)description;
@property(readonly, copy, nonatomic) NSURL *fileURL;

@end

