//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, GTSignature, NSString;

@interface GTNote : NSObject
{
    struct git_note *_note;
}

+ (id)defaultReferenceNameForRepository:(id)arg1 error:(id *)arg2;
- (id)init;
- (id)initWithTargetGitOID:(struct git_oid *)arg1 repository:(struct git_repository *)arg2 referenceName:(const char *)arg3 error:(id *)arg4;
- (id)initWithTargetOID:(id)arg1 repository:(id)arg2 referenceName:(id)arg3 error:(id *)arg4;
@property(readonly, nonatomic) GTOID *targetOID;
@property(readonly, nonatomic) GTSignature *committer;
@property(readonly, nonatomic) GTSignature *author;
@property(readonly, nonatomic) NSString *note;
- (struct git_note *)git_note;
- (void)dealloc;
- (id)description;

@end

