//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, GTRepository, NSString;

@interface GTObject : NSObject
{
    GTRepository *_repository;
    struct git_object *_git_object;
}

+ (id)objectWithObj:(struct git_object *)arg1 inRepository:(id)arg2;
+ (id)objectWithTreeEntry:(id)arg1 error:(id *)arg2;
+ (id)objectWithIndexEntry:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) struct git_object *git_object; // @synthesize git_object=_git_object;
@property(readonly, nonatomic) GTRepository *repository; // @synthesize repository=_repository;
- (void).cxx_destruct;
- (id)objectByPeelingToType:(int)arg1 error:(id *)arg2;
- (id)odbObjectWithError:(id *)arg1;
@property(readonly, nonatomic) NSString *shortSHA;
@property(readonly, nonatomic) NSString *SHA;
@property(readonly, nonatomic) GTOID *OID;
@property(readonly, nonatomic) NSString *type;
- (id)initWithObj:(struct git_object *)arg1 inRepository:(id)arg2;
- (id)init;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;
- (id)description;
- (id)initWithTreeEntry:(id)arg1 error:(id *)arg2;
- (id)initWithIndexEntry:(id)arg1 error:(id *)arg2;

@end

