//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, GTRepository;

@interface GTOdbObject : NSObject
{
    GTRepository *_repository;
    struct git_odb_object *_git_odb_object;
}

@property(readonly, nonatomic) struct git_odb_object *git_odb_object; // @synthesize git_odb_object=_git_odb_object;
@property(readonly, nonatomic) GTRepository *repository; // @synthesize repository=_repository;
- (void).cxx_destruct;
@property(readonly, nonatomic) GTOID *OID;
- (id)data;
- (unsigned long long)length;
- (int)type;
- (id)shaHash;
- (id)initWithOdbObj:(struct git_odb_object *)arg1 repository:(id)arg2;
- (id)init;
- (id)description;
- (void)dealloc;

@end

