//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface GTOID : NSObject <NSCopying>
{
    struct git_oid _git_oid;
}

+ (id)oidWithSHACString:(const char *)arg1;
+ (id)oidWithSHA:(id)arg1;
+ (id)oidWithGitOid:(const struct git_oid *)arg1;
+ (id)OIDByHashingData:(id)arg1 type:(int)arg2 error:(id *)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
@property(readonly, nonatomic, getter=isZero) BOOL zero;
- (id)initWithSHACString:(const char *)arg1;
- (id)initWithSHACString:(const char *)arg1 error:(id *)arg2;
- (id)initWithSHA:(id)arg1;
- (id)initWithSHA:(id)arg1 error:(id *)arg2;
- (id)initWithGitOid:(const struct git_oid *)arg1;
- (id)init;
@property(readonly, copy, nonatomic) NSString *SHA;
- (const struct git_oid *)git_oid;

@end

