//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, GTReflog, GTRepository, NSString;

@interface GTReference : NSObject
{
    GTRepository *_repository;
    struct git_reference *_git_reference;
}

+ (BOOL)isValidReferenceName:(id)arg1;
+ (id)invalidReferenceError;
+ (id)referenceByResolvingSymbolicReference:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) struct git_reference *git_reference; // @synthesize git_reference=_git_reference;
@property(readonly, nonatomic) GTRepository *repository; // @synthesize repository=_repository;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
@property(readonly, nonatomic) GTReflog *reflog;
- (id)reloadedReferenceWithError:(id *)arg1;
@property(readonly, nonatomic) GTOID *OID;
@property(readonly, nonatomic) const struct git_oid *git_oid;
- (id)resolvedReferenceWithError:(id *)arg1;
- (BOOL)deleteWithError:(id *)arg1;
- (id)referenceByUpdatingTarget:(id)arg1 message:(id)arg2 error:(id *)arg3;
@property(readonly, copy, nonatomic) GTOID *targetOID;
@property(readonly, copy, nonatomic) GTReference *resolvedReference;
@property(readonly, copy, nonatomic) id resolvedTarget;
@property(readonly, copy, nonatomic) id unresolvedTarget;
@property(readonly, nonatomic) long long referenceType;
- (id)referenceByRenaming:(id)arg1 error:(id *)arg2;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, nonatomic, getter=isNote) BOOL note;
@property(readonly, nonatomic, getter=isTag) BOOL tag;
@property(readonly, nonatomic, getter=isBranch) BOOL branch;
- (id)initWithGitReference:(struct git_reference *)arg1 repository:(id)arg2;
- (id)initByResolvingSymbolicReference:(id)arg1 error:(id *)arg2;
- (id)init;
@property(readonly, nonatomic, getter=isRemote) BOOL remote;
- (void)dealloc;

@end

