//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTReference;

@interface GTReflog : NSObject
{
    struct git_reflog *_git_reflog;
    GTReference *_reference;
}

@property(readonly, nonatomic) GTReference *reference; // @synthesize reference=_reference;
@property(readonly, nonatomic) struct git_reflog *git_reflog; // @synthesize git_reflog=_git_reflog;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long entryCount;
- (id)entryAtIndex:(unsigned long long)arg1;
- (BOOL)writeEntryWithCommitter:(id)arg1 message:(id)arg2 error:(id *)arg3;
- (id)initWithReference:(id)arg1;
- (id)init;
- (void)dealloc;

@end

