//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, GTReflog, GTSignature, NSString;

@interface GTReflogEntry : NSObject
{
    const struct git_reflog_entry *_git_reflog_entry;
    GTReflog *_reflog;
}

@property(readonly, nonatomic) GTReflog *reflog; // @synthesize reflog=_reflog;
@property(readonly, nonatomic) const struct git_reflog_entry *git_reflog_entry; // @synthesize git_reflog_entry=_git_reflog_entry;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *message;
@property(readonly, nonatomic) GTSignature *committer;
@property(readonly, nonatomic) GTOID *updatedOID;
@property(readonly, nonatomic) GTOID *previousOID;
- (id)initWithGitReflogEntry:(const struct git_reflog_entry *)arg1 reflog:(id)arg2;

@end

