//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTRepository, NSArray, NSString;

@interface GTRemote : NSObject
{
    BOOL _updatesFetchHead;
    int _autoTag;
    GTRepository *_repository;
    struct git_remote *_git_remote;
}

+ (BOOL)isValidRemoteName:(id)arg1;
+ (id)remoteWithName:(id)arg1 inRepository:(id)arg2 error:(id *)arg3;
+ (id)createRemoteWithName:(id)arg1 URLString:(id)arg2 inRepository:(id)arg3 error:(id *)arg4;
@property(readonly, nonatomic) struct git_remote *git_remote; // @synthesize git_remote=_git_remote;
@property(nonatomic) int autoTag; // @synthesize autoTag=_autoTag;
@property(nonatomic) BOOL updatesFetchHead; // @synthesize updatesFetchHead=_updatesFetchHead;
@property(readonly, nonatomic) GTRepository *repository; // @synthesize repository=_repository;
- (void).cxx_destruct;
- (BOOL)addFetchRefspec:(id)arg1 error:(id *)arg2;
- (BOOL)updatePushURLString:(id)arg1 error:(id *)arg2;
- (BOOL)updateURLString:(id)arg1 error:(id *)arg2;
@property(readonly, copy, nonatomic) NSArray *pushRefspecs;
@property(readonly, copy, nonatomic) NSArray *fetchRefspecs;
- (BOOL)rename:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic, getter=isConnected) BOOL connected;
@property(copy, nonatomic) NSString *pushURLString;
- (void)setURLString:(id)arg1;
@property(readonly, copy, nonatomic) NSString *URLString;
@property(readonly, copy, nonatomic) NSString *name;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithGitRemote:(struct git_remote *)arg1 inRepository:(id)arg2;
- (id)init;

@end

