//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString, NSTimeZone;

@interface GTSignature : NSObject
{
    struct git_signature *_git_signature;
}

@property(readonly, nonatomic) struct git_signature *git_signature; // @synthesize git_signature=_git_signature;
@property(readonly, copy, nonatomic) NSTimeZone *timeZone;
@property(readonly, nonatomic) NSDate *time;
@property(readonly, copy, nonatomic) NSString *email;
@property(readonly, copy, nonatomic) NSString *name;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)initWithName:(id)arg1 email:(id)arg2 time:(id)arg3;
- (id)initWithGitSignature:(const struct git_signature *)arg1;
- (void)dealloc;

@end

