//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTDiffFile;

@interface GTStatusDelta : NSObject
{
    GTDiffFile *_oldFile;
    GTDiffFile *_newFile;
    long long _status;
    double _similarity;
}

@property(readonly, nonatomic) double similarity; // @synthesize similarity=_similarity;
@property(readonly, nonatomic) long long status; // @synthesize status=_status;
@property(readonly, copy, nonatomic) GTDiffFile *newFile; // @synthesize newFile=_newFile;
@property(readonly, copy, nonatomic) GTDiffFile *oldFile; // @synthesize oldFile=_oldFile;
- (void).cxx_destruct;
- (id)initWithGitDiffDelta:(const CDStruct_10a53f2e *)arg1;
- (id)init;

@end

