//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, GTRepository, NSString;

@interface GTSubmodule : NSObject
{
    GTRepository *_parentRepository;
    struct git_submodule *_git_submodule;
}

@property(readonly, nonatomic) struct git_submodule *git_submodule; // @synthesize git_submodule=_git_submodule;
@property(readonly, nonatomic) GTRepository *parentRepository; // @synthesize parentRepository=_parentRepository;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (BOOL)addToIndex:(id *)arg1;
- (BOOL)writeToParentConfigurationDestructively:(BOOL)arg1 error:(id *)arg2;
- (id)submoduleRepository:(id *)arg1;
- (BOOL)sync:(id *)arg1;
- (BOOL)reload:(id *)arg1;
- (long long)status:(id *)arg1;
- (long long)statusWithIgnoreRule:(long long)arg1 error:(id *)arg2;
- (id)initWithGitSubmodule:(struct git_submodule *)arg1 parentRepository:(id)arg2;
- (id)init;
- (void)dealloc;
@property(readonly, copy, nonatomic) NSString *URLString;
@property(readonly, copy, nonatomic) NSString *path;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, nonatomic) GTOID *workingDirectoryOID;
@property(readonly, nonatomic) GTOID *HEADOID;
@property(readonly, nonatomic) GTOID *indexOID;
- (id)submoduleByUpdatingIgnoreRule:(long long)arg1 error:(id *)arg2;
@property(readonly, nonatomic) long long ignoreRule;

@end

