//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ObjectiveGit/GTObject.h>

@class GTSignature, NSString;

@interface GTTag : GTObject
{
}

- (BOOL)delete:(id *)arg1;
- (id)objectByPeelingTagError:(id *)arg1;
- (struct git_tag *)git_tag;
@property(readonly, nonatomic) GTSignature *tagger;
@property(readonly, nonatomic) int targetType;
@property(readonly, nonatomic) GTObject *target;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) NSString *message;
- (id)description;

@end

