//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTOID, GTTree, NSString;

@interface GTTreeEntry : NSObject
{
    GTTree *_tree;
    struct git_tree_entry *_git_tree_entry;
}

+ (id)entryWithEntry:(const struct git_tree_entry *)arg1 parentTree:(id)arg2 error:(id *)arg3;
@property(readonly, nonatomic) struct git_tree_entry *git_tree_entry; // @synthesize git_tree_entry=_git_tree_entry;
@property(readonly, nonatomic) GTTree *tree; // @synthesize tree=_tree;
- (void).cxx_destruct;
- (id)GTObject:(id *)arg1;
- (id)repository;
- (id)typeString;
@property(readonly, nonatomic) int type;
@property(readonly, copy, nonatomic) NSString *SHA;
@property(readonly, nonatomic) GTOID *OID;
@property(readonly, nonatomic) long long attributes;
@property(readonly, copy, nonatomic) NSString *name;
- (id)initWithEntry:(const struct git_tree_entry *)arg1 parentTree:(id)arg2 error:(id *)arg3;
- (void)dealloc;
- (BOOL)isEqualToEntry:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;

@end

