//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ObjectiveGit/GTObject.h>

@class NSArray;

@interface GTTree : GTObject
{
}

- (id)merge:(id)arg1 ancestor:(id)arg2 error:(id *)arg3;
@property(readonly, nonatomic) NSArray *entries;
- (BOOL)enumerateEntriesWithOptions:(long long)arg1 error:(id *)arg2 block:(CDUnknownBlockType)arg3;
- (struct git_tree *)git_tree;
- (id)entryWithPath:(id)arg1 error:(id *)arg2;
- (id)entryWithName:(id)arg1;
- (id)entryAtIndex:(unsigned long long)arg1;
- (id)createEntryWithEntry:(const struct git_tree_entry *)arg1 error:(id *)arg2;
@property(readonly, nonatomic) unsigned long long entryCount;
- (id)description;

@end

