//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTRepository;

@interface GTTreeBuilder : NSObject
{
    struct git_treebuilder *_git_treebuilder;
    GTRepository *_repository;
}

@property(readonly, nonatomic) GTRepository *repository; // @synthesize repository=_repository;
@property(readonly, nonatomic) struct git_treebuilder *git_treebuilder; // @synthesize git_treebuilder=_git_treebuilder;
- (void).cxx_destruct;
- (id)writeTree:(id *)arg1;
- (BOOL)removeEntryWithFileName:(id)arg1 error:(id *)arg2;
- (id)addEntryWithOID:(id)arg1 fileName:(id)arg2 fileMode:(long long)arg3 error:(id *)arg4;
- (id)addEntryWithData:(id)arg1 fileName:(id)arg2 fileMode:(long long)arg3 error:(id *)arg4;
- (id)entryWithFileName:(id)arg1;
- (void)filter:(CDUnknownBlockType)arg1;
- (void)clear;
- (void)dealloc;
- (id)initWithTree:(id)arg1 repository:(id)arg2 error:(id *)arg3;
- (id)init;
@property(readonly, nonatomic) unsigned long long entryCount;

@end

