//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (Git)
+ (id)git_dataWithBuffer:(CDStruct_8bf61218 *)arg1;
+ (id)git_dataWithOid:(struct git_oid *)arg1;
- (BOOL)git_isBinary;
- (BOOL)git_containsNUL;
- (CDStruct_8bf61218)git_buf;
- (BOOL)git_getOid:(struct git_oid *)arg1 error:(id *)arg2;
@end

