//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (GTTimeAdditions)
+ (id)gt_dateFromGitTime:(struct git_time)arg1;
- (struct git_time)gt_gitTimeUsingTimeZone:(id)arg1;
@end

