//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, NSString;

@interface PROAbstractConnection : NSObject
{
    int _fileDescriptor;
    NSString *_socketPath;
    NSObject<OS_dispatch_queue> *_listeningQueue;
    NSMutableDictionary *_channelQueues;
    NSObject<OS_dispatch_group> *_messagesGroup;
    NSMutableDictionary *_queuedMessages;
}

+ (id)socketPathForSketch:(id)arg1;
+ (id)withSocketPathForSketch:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *queuedMessages; // @synthesize queuedMessages=_queuedMessages;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *messagesGroup; // @synthesize messagesGroup=_messagesGroup;
@property(retain, nonatomic) NSMutableDictionary *channelQueues; // @synthesize channelQueues=_channelQueues;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *listeningQueue; // @synthesize listeningQueue=_listeningQueue;
@property(nonatomic) int fileDescriptor; // @synthesize fileDescriptor=_fileDescriptor;
@property(copy, nonatomic) NSString *socketPath; // @synthesize socketPath=_socketPath;
- (void).cxx_destruct;
- (id)readData:(id)arg1;
- (void)sendMessageOnQueue:(id)arg1 channel:(id)arg2 channelQueue:(id)arg3;
- (void)sendMessage:(id)arg1 channel:(id)arg2 channelId:(id)arg3;
- (id)createChannelQueue:(id)arg1;
- (void)invalidateOnQueue;
- (void)invalidate;
- (void)dealloc;
- (id)initWithSocketPath:(id)arg1;

@end

