//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PROAppUtils : NSObject
{
}

+ (id)info:(id)arg1;
+ (void)openAndWait:(id)arg1 forForeground:(BOOL)arg2 forTimeout:(int)arg3;
+ (void)open:(id)arg1 forForeground:(BOOL)arg2;
+ (void)quitAndWait:(id)arg1 forTimeout:(int)arg2;
+ (void)quit:(id)arg1;
+ (void)hide:(id)arg1;
+ (BOOL)isRunning:(id)arg1 forTimeout:(int)arg2;
+ (BOOL)isInstalled:(id)arg1;

@end

