//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSDK/PROSketchMessage.h>

@class NSDictionary, NSString;

@interface PROConfigMessage : PROSketchMessage
{
    BOOL _cliFileCreationEnabled;
}

@property(nonatomic) BOOL cliFileCreationEnabled; // @synthesize cliFileCreationEnabled=_cliFileCreationEnabled;
@property(readonly, nonatomic) BOOL librariesEnabled;
@property(readonly, nonatomic) NSString *cliPath;
@property(readonly, nonatomic) NSString *storePath;
@property(readonly, nonatomic) NSString *env;
@property(readonly, nonatomic) NSDictionary *newConfig;
- (id)initWithEnv:(id)arg1 storePath:(id)arg2 cliPath:(id)arg3 librariesEnabled:(BOOL)arg4 cliFileCreationEnabled:(BOOL)arg5;

@end

