//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileHandle;

@interface PRODebugLogger : NSObject
{
    NSFileHandle *_logHandle;
}

+ (id)sharedLogger;
@property(retain, nonatomic) NSFileHandle *logHandle; // @synthesize logHandle=_logHandle;
- (void).cxx_destruct;
- (id)handle;
- (void)log:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

