//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PROFileWrapperProtocol.h"

@class NSData, NSString;

@interface PRODrawingResource : NSObject <PROFileWrapperProtocol>
{
    NSString *_key;
    NSData *_resourceData;
}

+ (id)fromFileWrapper:(id)arg1;
+ (id)wrapperKey;
@property(retain, nonatomic) NSData *resourceData; // @synthesize resourceData=_resourceData;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (id)fileWrapper;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

