//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PROFileWrapperProtocol.h"

@class NSDictionary, NSNumber, NSString;

@interface PRODrawingItem : NSObject <PROFileWrapperProtocol>
{
    NSString *_identifier;
    NSString *_name;
    NSString *_type;
    NSDictionary *_meta;
    NSNumber *_version;
    id _data;
    NSString *_fileWrapperKey;
}

+ (id)drawingItemWithIdentifier:(id)arg1 name:(id)arg2 type:(id)arg3 data:(id)arg4;
+ (id)fromFileWrapper:(id)arg1;
+ (id)wrapperKey;
@property(copy, nonatomic) NSString *fileWrapperKey; // @synthesize fileWrapperKey=_fileWrapperKey;
@property(retain, nonatomic) id data; // @synthesize data=_data;
@property(copy, nonatomic) NSNumber *version; // @synthesize version=_version;
@property(retain, nonatomic) NSDictionary *meta; // @synthesize meta=_meta;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)fileWrapper;
- (id)preferredFilename;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

