//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PROFileWrapperProtocol.h"

@class NSNumber, NSString;

@interface PRODrawingInfo : NSObject <PROFileWrapperProtocol>
{
    NSString *_documentIdentifier;
    NSString *_documentType;
    NSString *_applicationVersion;
    NSNumber *_applicationBuildNumber;
    NSNumber *_applicationDocumentVersion;
    NSString *_abstractVersion;
    NSNumber *_version;
    NSString *_name;
}

+ (id)fromFileWrapper:(id)arg1;
+ (id)wrapperKey;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSNumber *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *abstractVersion; // @synthesize abstractVersion=_abstractVersion;
@property(copy, nonatomic) NSNumber *applicationDocumentVersion; // @synthesize applicationDocumentVersion=_applicationDocumentVersion;
@property(copy, nonatomic) NSNumber *applicationBuildNumber; // @synthesize applicationBuildNumber=_applicationBuildNumber;
@property(copy, nonatomic) NSString *applicationVersion; // @synthesize applicationVersion=_applicationVersion;
@property(copy, nonatomic) NSString *documentType; // @synthesize documentType=_documentType;
@property(copy, nonatomic) NSString *documentIdentifier; // @synthesize documentIdentifier=_documentIdentifier;
- (void).cxx_destruct;
- (id)toDictionary;
- (id)fileWrapper;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

