//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PROFileWrapperProtocol.h"

@class NSMutableDictionary, NSString;

@interface PRODrawingSharedData : NSObject <PROFileWrapperProtocol>
{
    NSMutableDictionary *_collections;
}

+ (id)fromFileWrapper:(id)arg1;
+ (id)wrapperKey;
@property(retain, nonatomic) NSMutableDictionary *collections; // @synthesize collections=_collections;
- (void).cxx_destruct;
- (id)fileWrapper;
- (id)collectionNames;
- (id)sharedDataCollectionWithName:(id)arg1;
- (void)addSharedDataCollection:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

