//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PROFileWrapperProtocol.h"

@class NSString, PRODrawingDataCollection, PRODrawingInfo, PRODrawingManifest, PRODrawingResourcesCollection, PRODrawingSharedData;

@interface PRODrawing : NSObject <PROFileWrapperProtocol>
{
    PRODrawingResourcesCollection *_resources;
    PRODrawingSharedData *_sharedData;
    PRODrawingDataCollection *_data;
    PRODrawingInfo *_info;
    PRODrawingManifest *_manifest;
}

+ (id)fromFileWrapper:(id)arg1;
+ (id)wrapperKey;
@property(retain, nonatomic) PRODrawingManifest *manifest; // @synthesize manifest=_manifest;
@property(retain, nonatomic) PRODrawingInfo *info; // @synthesize info=_info;
@property(retain, nonatomic) PRODrawingDataCollection *data; // @synthesize data=_data;
@property(retain, nonatomic) PRODrawingSharedData *sharedData; // @synthesize sharedData=_sharedData;
@property(retain, nonatomic) PRODrawingResourcesCollection *resources; // @synthesize resources=_resources;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL isLegacy;
- (id)fileWrapper;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

