//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSDK/PROOpenAbstractFileMessage.h>

@interface PROExportAbstractFileMessage : PROOpenAbstractFileMessage
{
}

- (id)initWithSavePath:(id)arg1 projectId:(id)arg2 baseSHA:(id)arg3 branchId:(id)arg4 branchName:(id)arg5 projectName:(id)arg6 SHA:(id)arg7 abstractFilePath:(id)arg8;

@end

