//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSDK/PROSketchMessage.h>

@class NSArray, NSNumber, NSString;

@interface PROExportBitmapFileMessage : PROSketchMessage
{
}

@property(readonly, nonatomic) NSString *trace;
@property(readonly, nonatomic) NSNumber *scale;
@property(readonly, nonatomic) NSString *outputPathFormat;
@property(readonly, nonatomic) NSArray *layerIds;
@property(readonly, nonatomic) NSNumber *layerIdsCount;
@property(readonly, nonatomic) NSString *abstractFilePath;
@property(readonly, nonatomic) NSString *SHA;
- (id)initWithSHA:(id)arg1 abstractFilePath:(id)arg2 layers:(id)arg3 outputPathFormat:(id)arg4 scale:(id)arg5;

@end

