//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTRepository, NSString, NSURL;

@interface PROGitController : NSObject
{
    GTRepository *_repo;
    NSString *_currentSHA;
    NSString *_previousBranchName;
    NSURL *_repoURL;
}

+ (id)gitControllerForDocumentURL:(id)arg1;
@property(retain, nonatomic) NSURL *repoURL; // @synthesize repoURL=_repoURL;
@property(copy, nonatomic) NSString *previousBranchName; // @synthesize previousBranchName=_previousBranchName;
@property(copy, nonatomic) NSString *currentSHA; // @synthesize currentSHA=_currentSHA;
@property(retain, nonatomic) GTRepository *repo; // @synthesize repo=_repo;
- (void).cxx_destruct;
- (void)setupRepo;
- (id)headSHAForBranch:(id)arg1;
- (id)shaForPath:(id)arg1 commitSha:(id)arg2;
- (id)documentPathRelativeToRepo:(id)arg1;
- (void)printDiff:(id)arg1;
- (id)pathForLayer:(id)arg1 documentURL:(id)arg2;
- (id)workingTreeDiff;
- (BOOL)layerHasChanges:(id)arg1 documentURL:(id)arg2;
- (BOOL)fileHasChanges:(id)arg1;
- (BOOL)hasChanges;
- (id)branchMetaName:(id)arg1;
- (id)currentBranchName;
- (id)currentBranch;
- (id)headSHA;
- (id)initWithRepoURL:(id)arg1;
- (id)fileWrapperForPath:(id)arg1 sha:(id)arg2;
- (id)fileWrapperForFileSha:(id)arg1;
- (id)fileWrapperBlobForFileSha:(id)arg1 withName:(id)arg2;

@end

