//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSDK/PROSketchMessage.h>

@class NSArray, NSNumber, NSString;

@interface PROGeneratePreviewsMessage : PROSketchMessage
{
    NSArray *_objectIds;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *trace;
@property(readonly, nonatomic) NSNumber *scale;
@property(readonly, nonatomic) NSArray *objectIds; // @synthesize objectIds=_objectIds;
@property(readonly, nonatomic) NSNumber *objectIdsCount;
@property(readonly, nonatomic) NSString *outputPathFormat;
@property(readonly, nonatomic) NSString *filePath;

@end

