//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSDK/PROSketchMessage.h>

@class NSString;

@interface PROOpenAbstractFileMessage : PROSketchMessage
{
}

@property(readonly, nonatomic) NSString *trace;
@property(readonly, nonatomic) NSString *layerId;
@property(readonly, nonatomic) NSString *abstractFilePath;
@property(readonly, nonatomic) NSString *SHA;
@property(readonly, nonatomic) NSString *projectId;
@property(readonly, nonatomic) NSString *projectName;
@property(readonly, nonatomic) NSString *branchName;
@property(readonly, nonatomic) NSString *branchId;
@property(readonly, nonatomic) NSString *baseSHA;
@property(readonly, nonatomic) NSString *savePath;
- (id)initWithSavePath:(id)arg1 projectId:(id)arg2 baseSHA:(id)arg3 branchId:(id)arg4 branchName:(id)arg5 projectName:(id)arg6 SHA:(id)arg7 abstractFilePath:(id)arg8 layerId:(id)arg9;

@end

