//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AbstractSDK/PROSketchMessage.h>

@class NSString;

@interface PROOpenFilePathMessage : PROSketchMessage
{
}

@property(readonly, nonatomic) NSString *trace;
@property(readonly, nonatomic) NSString *focusedObjectId;
@property(readonly, nonatomic) NSString *filePath;
- (id)init;

@end

