//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PROPropellerFileSaver : NSObject
{
}

- (void)save:(id)arg1 toPath:(id)arg2 isTerminating:(BOOL)arg3 finished:(CDUnknownBlockType)arg4;
- (void)save:(id)arg1 toPath:(id)arg2 finished:(CDUnknownBlockType)arg3;
- (void)save:(id)arg1 metadata:(id)arg2 isTerminating:(BOOL)arg3 finished:(CDUnknownBlockType)arg4;

@end

