//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface PROSketchMessage : NSObject
{
    NSString *_type;
    NSMutableDictionary *_info;
}

+ (id)fromJSONData:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *info; // @synthesize info=_info;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (BOOL)isPing;
- (BOOL)isFinishedMessage;
- (id)description;
- (id)serializeToJSON;
- (id)progressMessage:(id)arg1;
- (id)finishedMessage:(id)arg1;
- (void)changeIdentifier:(id)arg1;
@property(readonly, nonatomic) NSString *identifier;
- (id)initWithType:(id)arg1 info:(id)arg2;
- (id)init;

@end

