//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableDictionary.h"

@interface PROSortedKeyMutableDictionary : NSMutableDictionary
{
    NSMutableDictionary *_internalDictionary;
}

+ (id)dictionary;
@property(retain, nonatomic) NSMutableDictionary *internalDictionary; // @synthesize internalDictionary=_internalDictionary;
- (void).cxx_destruct;
- (id)archivedObjectWithPROJSONCoder:(id)arg1;
- (id)keyEnumerator;
- (id)objectForKey:(id)arg1;
- (unsigned long long)count;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)initWithObjects:(const id *)arg1 forKeys:(const id *)arg2 count:(unsigned long long)arg3;

@end

