//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PROGitController;

@interface PROSketchFileProcessingPipeline : NSObject
{
    PROGitController *_gitController;
}

@property(retain, nonatomic) PROGitController *gitController; // @synthesize gitController=_gitController;
- (void).cxx_destruct;
- (id)processDrawing:(id)arg1 sourcePath:(id)arg2;
- (id)initWithGitController:(id)arg1;

@end

