//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PROSketchObjectGraphUtils : NSObject
{
    NSString *_sketchVersion;
}

@property(copy, nonatomic) NSString *sketchVersion; // @synthesize sketchVersion=_sketchVersion;
- (void).cxx_destruct;
- (id)resolveKeyPath:(id)arg1;
- (id)createSketchArrayFromArray:(id)arg1;
- (id)safeValueForKeyPath:(id)arg1 from:(id)arg2;
- (void)enumerateLayers:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)enumerateLayers:(id)arg1 recurse:(BOOL)arg2 block:(CDUnknownBlockType)arg3;
- (id)layers:(id)arg1;
- (void)enumeratePages:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)pages:(id)arg1;
- (id)initWithSketchVersion:(id)arg1;

@end

